### ISSUE TITLE
typo at: https://w3c.github.io/N3/spec/#whitespace

### ISSUE THREAD

**Issue by pmario** [w3c/N3#108]
It says: 

>White space ([WS production](https://w3c.github.io/N3/spec/#grammar-production-WS)) is used to separate terminals. The amount and type of white space (e.g., **newline (%20) or space (%0A))** is only significant within terminals.

I did highlight the elements I think should be the other way around. `%20` is space and `%0A` is newline

**Comment by william-vw** [comment]
Thanks Mario, fixed now in [86f4634](https://github.com/w3c/N3/commit/86f46346ba0a0d21a35ea110416d1f33dae1911f).
