### ISSUE TITLE
@union/@intersection Keywords

### ISSUE THREAD

**Issue by AdamSobieski** [w3c/N3#114]
Hello. With respect to the [language-integrated semantic templates](https://github.com/w3c/N3/issues/110) proposal, the n-ary operations of graph-based union and intersection could be provided for users with the keywords proposed here.

The following examples show how `@union` and `@intersection` keywords could function with templates:

```turtle
ex:ng3??(?kb ?x ?y) :graph
{
    @union
    {
        ex:ng1??(?kb ?x ?y) .
        ex:ng2??(?kb ?x ?y) .
    }
} .
```
```turtle
ex:ng4??(?kb ?x ?y) :graph
{
    @intersection
    {
        ex:ng1??(?kb ?x ?y) .
        ex:ng2??(?kb ?x ?y) .
    }
} .
```

Any thoughts on these proposed N3 keywords? Thank you.

----
**See also:** https://github.com/w3c-cg/planning/discussions/27#discussioncomment-4406511

**Comment by josd** [comment]
Graph intersection is only partly covered by `graph:difference` in that there are only graphs in its subject and the order matters.
So I think it makes sense to have `graph:intersection` and also `graph:union` which both have subject that is a set of graphs.

**Comment by josd** [comment]
The [latest eye](https://github.com/eyereasoner/eye/releases/tag/v22.1216.2120) is adding experimental graph:intersection and graph:union built-ins.
So
```
@prefix graph: <http://www.w3.org/2000/10/swap/graph#> .
@prefix : <http://example.org/ns#> .

:graph1 :contains {
    :x :y _:z .
    :a :b :c .
} .


:graph2 :contains {
    :x :y _:z .
    :a :b :c .
} .

:graph3 :contains {
    :x :y :z .
    :a :b :c .
    :d :e :f .
} .

{
    :graph1 :contains ?g1 .
    :graph2 :contains ?g2 .
    :graph3 :contains ?g3 .

    ( ?g1 ?g2 ?g3 ) graph:intersection ?g4 .
    ( ?g1 ?g2 ?g3 ) graph:union ?g5 .

} => {
    :intersection :contains ?g4 .
    :union :contains ?g5 .
} .
```
gives
```
:intersection :contains {:a :b :c}.
:union :contains {:a :b :c. :d :e :f. :x :y :z. :x :y _:e_z_1. :x :y _:e_z_2}.
```

**Comment by josd** [comment]
> Currently I don't think we have a `graph:union` (or append) - @josd ?

There was indeed no `graph:union` but see https://github.com/w3c/N3/issues/114#issuecomment-1355638191
