### ISSUE TITLE
[Spec] built-in list

### ISSUE THREAD

**Issue by phochste** [w3c/N3#129]
Can we get in the spec (even if only temporarily) the list of built-ins back? I need an overview of all the built ins for programming reasons and refer to this list quite often to people. In the recent version of the spec this overview of built-ins was deleted.

**Comment by josd** [comment]
Fully agreed and I would even add the built-in specs to the spec!

**Comment by william-vw** [comment]
@phochste do you mean this part:
https://github.com/w3c/N3/blob/4414081a940234b6a6f5aa7bbae96242400741ab/spec/index.html#L845

**Comment by phochste** [comment]
Yes that is my cheat sheet.

**Comment by william-vw** [comment]
fixed in ffd0f0a5081798754e158a6666a95bfe1b85ceac
