### ISSUE TITLE
"string literal" vs "datatyped literal"

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/N3#132]
https://w3c.github.io/N3/spec/#literals
> ..need to be written as **string literals**. If the literal is not a string, its particular datatype must be indicated using the `^^` symbol and the corresponding [datatype IRI](https://www.w3.org/TR/xmlschema11-2/#built-in-datatypes).

I think that "string literal" means only `xsd:string`, so I propose to change this to:

> ..need to be written as **datatyped literals**, which are denoted as a string, followed by the `^^` symbol and the corresponding [datatype IRI](https://www.w3.org/TR/xmlschema11-2/#built-in-datatypes) (`xsd:string` is the default and can be omitted).

And later: change

> The language of the string literal 

to

> The language of a string literal

**Comment by william-vw** [comment]
@VladimirAlexiev thanks a lot for going over the spec. I think it would be more efficient if you create a PR so we don't misinterpret your comments (and have to go back and forth).

**Comment by william-vw** [comment]
fixed by https://github.com/w3c/N3/pull/154
