### ISSUE TITLE
xsd:int vs xsd:integer

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/N3#133]
https://w3c.github.io/N3/spec/#h-note-6

> Integers, decimals, doubles, and booleans **may** also be written as string literals with the appropriate [datatype IRI](https://www.w3.org/TR/xmlschema11-2/#built-in-datatypes) (e.g., **"8"^^xsd:int** or "true"^^xsd:boolean).

I think this should be changed to 
> Integers, decimals, doubles, and booleans **may** also be written as string literals with the appropriate [datatype IRI](https://www.w3.org/TR/xmlschema11-2/#built-in-datatypes) (e.g., **"8"^^xsd:integer** or "true"^^xsd:boolean).

because:
- `xsd:int` **must** be specified, 
- the earlier https://w3c.github.io/N3/spec/#example-9 shows "Integers, decimals, doubles, and booleans" and correctly states:
```ttl
:atomicNumber 2 ;               # xsd:integer
```

**Comment by domel** [comment]
Good catch. We should we following RDF 1.1, where `xsd:integer `is defined as a core datatype.

**Comment by VladimirAlexiev** [comment]
@domel what is "core"?

**Comment by domel** [comment]
See [RDF 1.1 Concepts and Abstract Syntax](https://www.w3.org/TR/rdf11-concepts/#xsd-datatypes) (The XML Schema Built-in Datatypes).

**Comment by william-vw** [comment]
fixed by https://github.com/w3c/N3/pull/155
