### ISSUE TITLE
No semicolon in IRI property lists; link to bnodeprplist

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/N3#134]
https://w3c.github.io/N3/spec/#iriprplist shows a feature I've long wanted to see:
```ttl
:spiderman 
  :enemyOf 
    [ id :green-goblin 
      :portrayedBy [ id :willem-dafoe
        a :Actor 
      ]
    ] ;
    :portrayedBy [ id :tobey-maguire
        a :Actor
    ] .
```
And explains:

> IRI property lists build on the [predicate object list](https://w3c.github.io/N3/spec/#polists) syntax to group statements about [IRIs](https://w3c.github.io/N3/spec/#dfn-absolute-iri). 

Right, they are very similar. But one must not use `;` ~
I think the spec should emphasize this, and maybe explain why `;` is not allowed here.

> One can use [objects lists](https://w3c.github.io/N3/spec/#object-lists-example) in this syntax as well.

Yes, I tried and using `,` to add objects works fine.

Also: this section should have a Note linking to https://w3c.github.io/N3/spec/#bnodeprplist.
just like that section links to this one.

**Comment by TallTed** [comment]
The indents of the example  aren't quite balanced.  For human consumption,
```
:spiderman 
  :enemyOf 
    [ id :green-goblin 
      :portrayedBy [ id :willem-dafoe
        a :Actor 
      ]
    ] ;
    :portrayedBy [ id :tobey-maguire
        a :Actor
    ] .
```
should be (note the last three lines)
```
:spiderman 
  :enemyOf 
    [ id :green-goblin 
      :portrayedBy [ id :willem-dafoe
        a :Actor 
      ]
    ] ;
  :portrayedBy [ id :tobey-maguire
    a :Actor
  ] .
```

**Comment by william-vw** [comment]
> 



> https://w3c.github.io/N3/spec/#iriprplist shows a feature I've long wanted to see:
> 
> ```turtle
> :spiderman 
>   :enemyOf 
>     [ id :green-goblin 
>       :portrayedBy [ id :willem-dafoe
>         a :Actor 
>       ]
>     ] ;
>     :portrayedBy [ id :tobey-maguire
>         a :Actor
>     ] .
> ```
> 
> And explains:
> 
> > IRI property lists build on the [predicate object list](https://w3c.github.io/N3/spec/#polists) syntax to group statements about [IRIs](https://w3c.github.io/N3/spec/#dfn-absolute-iri).
> 
> Right, they are very similar. But one must not use `;` ~ I think the spec should emphasize this, and maybe explain why `;` is not allowed here.

Please add a PR for this (e.g., would you put it in a separate note?)
