### ISSUE TITLE
Emphasize that blank node property lists cannot use `id`

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/N3#135]
https://w3c.github.io/N3/spec/#bnodeprplist gives an example, then a note:

> See also the [IRI property list](https://w3c.github.io/N3/spec/#iriprplist) syntax.

Being the busybody that I am, I tried to combine the two:
```ttl
@prefix ex: <http://example.org/#> .

ex:john ex:address [
  ex:street "Evergreen Terrace" ;
  ex:number 742 ;
  ex:town [id _:springfield ex:name "Springfield" ]
] .

ex:john ex:address [ex:town _:springfield].
```

But it's not allowed to use `id` with a blank node name. So I think change the above note to:

> Compare to the [IRI property list](https://w3c.github.io/N3/spec/#iriprplist) syntax. 
Note: you cannot use that syntax (the `id` keyword) with blank node identifiers.

**Comment by william-vw** [comment]
Unsure how many people would think of this :-) Feel free to make a PR so others can give their thoughts.
