### ISSUE TITLE
add "compoundliteral" as example in "blank-node-use-cases"

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/N3#136]
https://w3c.github.io/N3/spec/#x3-6-3-blank-node-use-cases
> **Composite information:** when describing composite pieces of information, such as street addresses, telephone numbers and dates

Add:

> ... Representing [Compound literals](https://w3c.github.io/N3/spec/#compoundliteral) is another typical use of this pattern.

**Comment by domel** [comment]
In principle, I agree. But we should remember about discussing about i18n in RDF 1.2. @VladimirAlexiev can you provide a PR?

**Comment by VladimirAlexiev** [comment]
@domel 
- this spec somewhat boldly talks about the new "text direction" work/ideas without giving any reference. I didn't post an issue, but maybe this needs to be fixed? It is highly nontrivial how `^^i18n:ar_EG-rtl` is magically "transformed to `^^rdf:langString`
- yes, I'll make some PRs

**Comment by gkellogg** [comment]
Probably best to suspend anything more on this until the RDF-star WG takes a direction; it _may_ make sense to take a different direction, but I think N3 should take it's lead from discussions/decisions there.

There are arguments against `i18n` and Compound Literals, but they have less impact on the ecosystem. The "_right_" way to do this may be at the model level, with a fourth element added for language-tagged literals, but that has it's own major consequences.

Track https://github.com/w3c/rdf-concepts/issues/9 an https://github.com/w3c/rdf-star-wg/blob/main/docs/text-direction.md.
