### ISSUE TITLE
utilize -> use; extra space in URL

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/N3#139]
The word `utilize` is used twice:
> An [N3 rule](https://w3c.github.io/N3/spec/#dfn-logical-implication) can also indicate which mode should be used, by using the appropriate predicate. Up until now, we have been utilizing =>,

> authors can utilize the [N3 Named Graphs extension](https://github.com/IDLabRese%20arch/N3NamedGraphSemantics);

I think the author got fed up with too many occurrences `use` in the sentence, so decided to flourish the writing by `utilize`.
But in the interests of uniformity and simplicity, please change to `use`.

BTW, there is an extraneous space in that last URL. The right URL is https://github.com/IDLabResearch/N3NamedGraphSemantics

**Comment by william-vw** [comment]
>BTW, there is an extraneous space in that last URL. The right URL is https://github.com/IDLabResearch/N3NamedGraphSemantics
Fixed in https://github.com/w3c/N3/pull/143
