### ISSUE TITLE
iterate & concatenation example

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/N3#142]
https://w3c.github.io/N3/spec/#iterate_example claims the output will be 
```
1. flash
2. superman
3. spiderman
```
But I think it will be something like this:
```
1. http://example.org/#flash<br />2. http://example.org/#superman<br />3. http://example.org/#spiderman<br />
```
I think you need to apply some function to extract the local name, 
and explain that `<br />` is a way to denote newline in HTML

**Comment by domel** [comment]
> explain that `<br />` is a way to denote newline in HTML

True, it should be `<br>` instead of `<br />`.

**Comment by william-vw** [comment]
@VladimirAlexiev @domel you should be able to add your corrections & updates to this PR: https://github.com/w3c/N3/pull/143

I applied one of your suggested corrections.

(or, feel free to create your own PR)

**Comment by VladimirAlexiev** [comment]
@domel `<br/>` is the newer better way to write `<br>`.
My point is that the concat outputs BRs, not new lines.

@william-vw thanks, I'll work on some patches.

**Comment by domel** [comment]
@VladimirAlexiev Yes, I'm referring to `<br>` becasue you mentioned it. And I disagree that `<br />` is newer better that `<br>`. HTML Living Standard (and W3C HTML5) propose two ways to write new lines: standard, popular one with HTML MIME type: `<br>`, and those who want to use XHTML (XML-based HTML) and use XHTML MIME type: `<br />`. Nowadays, almost no one serves web pages as XHTML (or XML). The vast majority use HTML, so `<br>` makes more sense. BTW, even if for some reason we want to glorify XHTML, the space before the slash is not needed.

**Comment by TallTed** [comment]
As long as we're nitpicking...

True, XHTML doesn't require the space in `<br />`, but the tooling you're pushing your XHTML through, including (still) some browsers may choke on `<br/>`. On the other hand, so far as I know, none choke on `<br />` when found in XHTML nor (again so far as I know) modern HTML.

Also, "MIME types" is the old name for what have been more properly called "Media Types" since [RFC 1590 in March 1994](https://www.rfc-editor.org/rfc/rfc1590).

**Comment by william-vw** [comment]
> But I think it will be something like this:
>
> 1. http://example.org/#flash<br />2. http://example.org/#superman<br />3. http://example.org/#spiderman<br />

Note that you can try all examples in the N3 editor (link at the right top of each example box):
https://w3c.github.io/N3/spec/#iterate_example

More specifically, the example will lead to:
```
:race :entries "0. :flash<br />".
:race :entries "1. :superman<br />".
:race :entries "2. :spiderman<br />".
```

But I felt the simplified list was easier to understand. This [PR commit](https://github.com/w3c/N3/pull/143/commits/4b859e0ff9dc49283e8db3a0be66c3734de84d07) removes the "<br />" tag and clarifies these results are the object values:

**Comment by william-vw** [comment]
fixed by PR https://github.com/w3c/N3/pull/143
