### ISSUE TITLE
Embedding N3 in XHTML documents 

### ISSUE THREAD

**Issue by domel** [w3c/N3#144]
In the spec:
> Editor's note
> Check this, I don't think that CDATA is required for XHTML any longer. See JSON-LD 1.1 . 

Yes, XHTML is XML, so code like `<https://example.org/>` is non-valid because of `<` and `>` characters. To solve this problem, there are two options: (1) predefined character entities (e.g. `&lt;`) or CDATA section. Note that the second one is easier to use with N3, Turtle, N-Triples, etc. Remember that above description is not about HTML. To sum up, we should remove that editor's note.

**Comment by william-vw** [comment]
fixed in 83d54ae
