### ISSUE TITLE
Track "text direction" proposals/work

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/N3#149]
(split off from #136, starting at https://github.com/w3c/N3/issues/136#issuecomment-1442024131)

The N3 spec boldly cites new ways to specify text-direction of language-tagged literals:

- https://w3c.github.io/N3/spec/#example-12
```
"الرجل العنكبوت"^^i18n:ar-eg_rtl
```
- https://w3c.github.io/N3/spec/#compoundliteral
```ttl
[
  rdf:value "الرجل العنكبوت" ;
  rdf:language "ar-eg" ;
  rdf:direction "rtl"
]
```

As @gkellogg says "There are arguments against i18n and Compound Literals".
- #148 adds a Note (warning) and links to relevant work
- This issue is to ensure closure when a decision is made on "text direction" in the other WGs. Track:
  - https://github.com/w3c/rdf-concepts/issues/9
  - https://github.com/w3c/rdf-star-wg/blob/main/docs/text-direction.md

**Comment by VladimirAlexiev** [comment]
BTW, if I add lang name `ttl` to the first code block above, the whole line is right-aligned:
```ttl
"الرجل العنكبوت"^^i18n:ar-eg_rtl
```

Magic? No, just some quirk of Github's syntax highlighter

**Comment by william-vw** [comment]
We already have an ongoing issue to track this work: https://github.com/w3c/N3/issues/127
