### ISSUE TITLE
Example 15/16 and RWD

### ISSUE THREAD

**Issue by domel** [w3c/N3#151]
Example 15 and Example 16 in the spec display problematically in mobile devices. Maybe `overflow-x:scroll` in CSS will help?

**Comment by TallTed** [comment]
Can you provide a screenshot of some problematic display?

Over time (not specific to these examples), I've found different issues in different browsers on different devices.  Much is testable and improvable with web developer tools like the Web Developer Extension and Stylebot. The former can preview a page in variously sized DIVs to emulate various devices, though it is limited to the browser in which the extension is installed. Both can allow CSS tweaks to be shown in your local browser without changing the live page until your changes are well tested. Perhaps these will help you test whether `overflow-x:scroll` makes a difference, through testing in a desktop browser with DIVs sized to match your mobile devices....

**Comment by domel** [comment]
Here you are ![IMG_20230228_201704](https://user-images.githubusercontent.com/114484/221956456-4f808486-267e-44c0-89c8-1b51e4b6546c.jpg)

To see the second example I should scroll to right, which is annoying.
The same issue is in Example 7 and Example 8.

**Comment by william-vw** [comment]
@domel @TallTed Please feel free to issue a PR to fix this problem.

**Comment by domel** [comment]
@william-vw see PR https://github.com/w3c/N3/pull/159

**Comment by william-vw** [comment]
thanks - merged the PR.
