### ISSUE TITLE
Description of datatyped literals needs more work

### ISSUE THREAD

**Issue by TallTed** [w3c/N3#160]
_Originally posted by @TallTed in https://github.com/w3c/N3/pull/154#discussion_r1131572503_
            Lines 493-495 of `spec/index.html` will need some additional work. 
```
                                                                                             These are represented as a string, 
        followed by the `^^` symbol and the corresponding <dfn data-cite="XMLSCHEMA11-2#built-in-datatypes">datatype IRI</dfn>.
        (`xsd:string` is the datatype IRI for strings; this is the default and can be omitted).
```
As it stands now, it suggests that `"test"^^` would be valid, as the string `"test"` is followed by `^^` and omits `xsd:string` (or more precisely, omits `http://www.w3.org/2001/XMLSchema#string`).

**Comment by william-vw** [comment]
@TallTed Feel free to propose a PR to fix the issue. Note that this section is non-normative.
