### ISSUE TITLE
Semantics of `has`

### ISSUE THREAD

**Issue by jeswr** [w3c/N3#176]
The semantics of `has` are not well defined in the spec. I'm guessing that `<a> has <b> <c> .` is the same as `<a> [ <b> <c> ] .` But I'm not sure.

**Comment by william-vw** [comment]
@jeswr You are right that this is not mentioned in the spec, aside from the grammar (the same for "is .. of" and "<-"). This is an oversight and should be corrected.

It is actually quite simple - `:a has :b :c` means `:a :b :c`. It's pretty useless but it made it into the current grammar, likely for backward compatibility. (I believe it was originally introduced for cases such as `william has father paul`, i.e., to clarify the meaning of certain property names.)

**Comment by jeswr** [comment]
Thanks for the answer - will leave open as a reminder to add a mention to the spec.

**Comment by william-vw** [comment]
Fixed by latest spec update.
