### ISSUE TITLE
List implementations

### ISSUE THREAD

**Issue by nichtich** [w3c/N3#192]
I happen to like reading specifications but I suppose more people want to start with some code. The [home page](https://w3c.github.io/N3/) should list known implementations. Best would be to include results against [the tests](https://github.com/w3c/N3/tree/master/tests) but any pointer would be better than nothing. I only found Gregg's [Ruby implementation](https://ruby-rdf.github.io/rdf-n3/) so far.

**Comment by gkellogg** [comment]
There is this [list of implementations](https://github.com/w3c/N3/blob/master/implementations.md), but it doesn't seem to be linked in the README.
