### ISSUE TITLE
N3 Syntax Issues

### ISSUE THREAD

**Issue by william-vw** [w3c/N3#21]
During our last few Skype meetings, we've been talking about the concrete N3 syntax given the [original BNF](https://www.w3.org/2000/10/swap/grammar/n3-report.html). A proposed goal here involves compatibility with [Turtle grammar](https://www.w3.org/TR/turtle/#sec-grammar) - i.e., each Turtle document should be valid N3 syntax.

We've been discussing the following issues:

(**1**) N3 allows subjects, predicates and objects to be [expressions](https://www.w3.org/2000/10/swap/grammar/n3-report.html#subject), whereas Turtle is more restrictive (for instance, Turtle does not allow a [subject to be a literal or boolean](https://www.w3.org/TR/turtle/#grammar-production-subject)). In RDF literals are only allowed in the object position. This kind of flexibility would be useful for e.g., builtins: one of the proposed NAF built-ins, forAllIn, requires a list as a predicate (see https://github.com/w3c/N3/issues/18#issuecomment-511210374).

Currently, we would advocate keeping the flexibility of N3 - this still supports any Turtle document (not vice-versa, but that is not the goal).

(**2**) the [keywords directive](https://www.w3.org/TeamSubmission/n3/#keywords) seems to overly complicate N3 parsing for little gain. One could also argue that it makes N3 documents harder to read since it's easy to forget which particular keywords were listed in the clause (i.e., causing confusion between qnames and keywords in N3 code). Hence, we would advocate dropping the keywords section in the N3 syntax.

(**3**) there are [certain keywords](https://www.w3.org/2000/10/swap/grammar/n3-report.html#predicate) such as _`@has` expression_ and _`@is` expression `@of`_ that can be used to more explicitly indicate a resource's property; e.g., william `@has` father paul ; paul `@is` father `@of` paul (inverse). They are highly unintuitive when the predicate name implies the reading direction (e.g., paul `@is` hasFather `@of`). It is clear that the first one is redundant; and N3 already has the [path syntax](https://www.w3.org/TeamSubmission/n3/#path) to traverse properties in the inverse direction. Hence, we'd propose to drop these two keywords.

(**4**) the original N3 BNF supports specific literals such as [date, dateTime](https://www.w3.org/2000/10/swap/grammar/n3-report.html#date), [rational and decimal](https://www.w3.org/2000/10/swap/grammar/n3-report.html#numericliteral) - we propose that these are not needed since they can be represented using RDF typed literals.

(**5**) some rather "sneaky" production rules:
Within cited formulas, N3 allows for the [last statement](https://www.w3.org/2000/10/swap/grammar/n3-report.html#statementtail) not to end with "." . It seems that this is a popular way of writing N3 formulas; we would choose to leave this as is.

Technically, the N3 syntax also allows for a ["dangling" semi-colon](https://www.w3.org/2000/10/swap/grammar/n3-report.html#propertylisttail) at the end of a statement, e.g., `<s> <p> <o> ;.`. Note that Turtle seemingly allows [infinite semicolons](https://www.w3.org/TR/turtle/#grammar-production-triples) in the same position, e.g., `<s> <p> <o> ;;;;;.`. While it it allows some laxity for N3 authors, it could cause confusion when people try to attach (non-existent) meaning to the extra characters. Currently, we're unsure what to do with this syntax since we're unsure what made the authors include this possibility (it is not possible for e.g., comma's within object lists) or whether it is an oversight.

**Comment by gkellogg** [comment]
> During our last few Skype meetings, we've been talking about the concrete N3 syntax given the [original BNF](https://www.w3.org/2000/10/swap/grammar/n3-report.html). A proposed goal here involves compatibility with [Turtle grammar](https://www.w3.org/TR/turtle/#sec-grammar) - i.e., each Turtle document should be valid N3 syntax.
> 
> We've been discussing the following issues:
> 
> (**1**) N3 allows subjects, predicates and objects to be [expressions](https://www.w3.org/2000/10/swap/grammar/n3-report.html#subject), whereas Turtle is more restrictive (for instance, Turtle does not allow a [subject to be a literal or boolean](https://www.w3.org/TR/turtle/#grammar-production-subject)). In RDF literals are only allowed in the object position. This kind of flexibility would be useful for e.g., builtins: one of the proposed NAF built-ins, forAllIn, requires a list as a predicate (see [#18 (comment)](https://github.com/w3c/N3/issues/18#issuecomment-511210374)).
> 
> Currently, we would advocate keeping the flexibility of N3 - this still supports any Turtle document (not vice-versa, but that is not the goal).

👍 

> (**2**) the [keywords directive](https://www.w3.org/TeamSubmission/n3/#keywords) seems to overly complicate N3 parsing for little gain. One could also argue that it makes N3 documents harder to read since it's easy to forget which particular keywords were listed in the clause (i.e., causing confusion between qnames and keywords in N3 code). Hence, we would advocate dropping the keywords section in the N3 syntax.

Note that `a` is a common bare keyword (`@a`), and `@a` is rarely or never used. The `a` form is quite useful. Otherwise 👍 

> (**3**) there are [certain keywords](https://www.w3.org/2000/10/swap/grammar/n3-report.html#predicate) such as _`@has` expression_ and _`@is` expression `@of`_ that can be used to more explicitly indicate a resource's property; e.g., william `@has` father paul ; paul `@is` father `@of` paul (inverse). They are highly unintuitive when the predicate name implies the reading direction (e.g., paul `@is` hasFather `@of`). It is clear that the first one is redundant; and N3 already has the [path syntax](https://www.w3.org/TeamSubmission/n3/#path) to traverse properties in the inverse direction. Hence, we'd propose to drop these two keywords.

`@is ... @of` (or`is ... of`) is quite useful, and many of us argued for it to be added to Turtle, in vain. Also, JSON-LD has `@reverse`, which can be eliminated in the syntax by associating it with a term. Inverse relationships are quite powerful.

> (**4**) the original N3 BNF supports specific literals such as [date, dateTime](https://www.w3.org/2000/10/swap/grammar/n3-report.html#date), [rational and decimal](https://www.w3.org/2000/10/swap/grammar/n3-report.html#numericliteral) - we propose that these are not needed since they can be represented using RDF typed literals.

Interestingly, although `date` and `dateTime` are defined, their not actually used in the grammar otherwise. `rational` was new to me, but it's unclear how it would be represented in the abstract RDF syntax.

Turtle also supports `decimal`, along with `integer` and `double`. (Due to JSON issues, JSON-LD only natively supports `integer` and `double`).

> (**5**) some rather "sneaky" production rules:
> Within cited formulas, N3 allows for the [last statement](https://www.w3.org/2000/10/swap/grammar/n3-report.html#statementtail) not to end with "." . It seems that this is a popular way of writing N3 formulas; we would choose to leave this as is.

This was allowed in a production for TriG as well, but only when part of a named-graph. In N3, I think it's also mostly used within formulae.

> Technically, the N3 syntax also allows for a ["dangling" semi-colon](https://www.w3.org/2000/10/swap/grammar/n3-report.html#propertylisttail) at the end of a statement, e.g., `<s> <p> <o> ;.`. Note that Turtle seemingly allows [infinite semicolons](https://www.w3.org/TR/turtle/#grammar-production-triples) in the same position, e.g., `<s> <p> <o> ;;;;;.`. While it it allows some laxity for N3 authors, it could cause confusion when people try to attach (non-existent) meaning to the extra characters. Currently, we're unsure what to do with this syntax since we're unsure what made the authors include this possibility (it is not possible for e.g., comma's within object lists) or whether it is an oversight.

This aids automated code generation, and the duplicated `;` is just a concession for parsers. I think removing it at this time would not be productive.

**Comment by william-vw** [comment]
@gkellogg 

> Note that a is a common bare keyword (@a), and @a is rarely or never used. The a form is quite useful. Otherwise +1

Yes, we were planning on supporting both `a` and `@a` just like `true` & `@true` and `false` & `@false`. I.e., allowing both the Turtle and N3 syntax here (latter for consistency mostly - as you said most people rely on "a").

> `@is` ... `@of` (oris ... of) is quite useful, and many of us argued for it to be added to Turtle, in vain. Also, JSON-LD has @reverse, which can be eliminated in the syntax by associating it with a term. Inverse relationships are quite powerful.

Note that N3 already has the [path syntax](https://www.w3.org/TeamSubmission/n3/#path) to traverse properties in the inverse direction, e.g., (based on N3 spec): `:nancy^fam:hasMother` (anyone who has nancy as mother). If we would write this using the is-of syntax: `:nancy @is :hasMother @of :joe` which it not very intuitive IMO - it only reads well when predicate names do not indicate direction.

**Comment by mielvds** [comment]
> 
> (**5**) some rather "sneaky" production rules:
> Within cited formulas, N3 allows for the [last statement](https://www.w3.org/2000/10/swap/grammar/n3-report.html#statementtail) not to end with "." . It seems that this is a popular way of writing N3 formulas; we would choose to leave this as is.

This is equivalent to Turtle no? But in case it would not be, I'd advise to follow Turtle here.

> Note that N3 already has the [path syntax](https://www.w3.org/TeamSubmission/n3/#path) to traverse properties in the inverse direction, e.g., (based on N3 spec): `:nancy^fam:hasMother` (anyone who has nancy as mother). If we would write this using the is-of syntax: `:nancy @is :hasMother @of :joe` which it not very intuitive IMO - it only reads well when predicate names do not indicate direction.

Since these are shorthands, I would at first sight only go for the path expressions. However, it kind of depends on how things like quantification will be done syntactically and how "common" this will make the "@" based syntax.

**Comment by william-vw** [comment]
> This is equivalent to Turtle no? But in case it would not be, I'd advise to follow Turtle here.

AFAICT Turtle requires every statement to end with a '.' Note that the goal is for N3 to "subsume" Turtle (i.e., all Turtle docs are valid N3 docs) so either solution would be suitable here.

**Comment by gkellogg** [comment]
> > (**5**) some rather "sneaky" production rules:
> > Within cited formulas, N3 allows for the [last statement](https://www.w3.org/2000/10/swap/grammar/n3-report.html#statementtail) not to end with "." . It seems that this is a popular way of writing N3 formulas; we would choose to leave this as is.
> 
> This is equivalent to Turtle no? But in case it would not be, I'd advise to follow Turtle here.

Turle has no equivalent of formulae, but TriG does. In Turtle, and in TriG outside of named graphs, statements must end with a “.”  Within TriG named graphs, the last statement can omit the “.”  iIRC, this is because of N3 practice, so we should continue to allow the same expression.

**Comment by mielvds** [comment]
> Turle has no equivalent of formulae, but TriG does. 

No, but syntactically you could view N3 formulae as triples that allow graphs as terms.

> In Turtle, and in TriG outside of named graphs, statements must end with a “.” 

Yet, within short hand blank nodes, they don't: https://www.w3.org/TR/turtle/examples/example2.ttl 

> Within TriG named graphs, the last statement can omit the “.” iIRC, this is because of N3 practice, so we should continue to allow the same expression.

Seems like the way to go indeed.

**Comment by ericprud** [comment]
Does anyone know why N3 paths aren't separated with '/'? That would be be compatible with SPARQL and compatible with Turtle which does not permit unescaped '/'s in [PN_LOCAL](https://www.w3.org/TR/turtle/#grammar-production-PN_LOCAL).

**Comment by william-vw** [comment]
You raise a good point and '/' would be more intuitive IMO. My best guess is that N3 was proposed before SPARQL property paths (2005 vs. 2010).The inverse syntax '^' seems identical however so perhaps there was some influencing

**Comment by mielvds** [comment]
I think we should align with SPARQL indeed. However, `!`cannot simply become `/`; paths cannot be attached to a subject AFAIK.  
The in N3 `x!p means [ is p of x ] `, wouldn't be `x/p` in SPARQL, but rather something like`x p _:o`. 

But this relationship should be explored in a separate issue. Maybe we should see if all property path expressions can be incorporated?  https://www.w3.org/TR/sparql11-query/#propertypaths

**Comment by william-vw** [comment]
@mielvds Note that, in N3, anything can be a path (s/p/o) - see the BNF here: https://www.w3.org/2000/10/swap/grammar/n3-report.html#expression. This is in contrast to SPARQL that only focuses on property paths.

You raise a good point on possibly integrating all (property) path expressions. Especially the alternative path expression seems quite useful; although it may pose implementation challenges since it essentially represents a disjunction. For SPARQL this is not a problem since they already have the UNION syntax. 

Please, feel free to open a new issue for this topic!

**Comment by mielvds** [comment]
> @mielvds Note that, in N3, anything can be a path (s/p/o) - see the BNF here: https://www.w3.org/2000/10/swap/grammar/n3-report.html#expression. This is in contrast to SPARQL that only focuses on property paths.
> 

Indeed, but do we know how useful that actually is?
Even in that case, I would still go for a superset of the SPARQL pp.

> You raise a good point on possibly integrating all (property) path expressions. Especially the alternative path expression seems quite useful; although it may pose implementation challenges since it essentially represents a disjunction. For SPARQL this is not a problem since they already have the UNION syntax.

Okay, proceed with caution.

> 
> Please, feel free to open a new issue for this topic!

Will do; let's no longer discuss path expressions here.

**Comment by william-vw** [comment]
While testing the new N3 grammar with the Eye test cases I came across the following cases:

1. non-labeled (for lack of a better word) bnodes, i.e., `_:` (e.g., [metastaticP.n3](http://eulersharp.sourceforge.net/2004/04test/metastaticP.n3))

2. quick-variables annotated with datatypes and language tags, i.e.,

- `?v^^xsd:int` (see e.g., [icalQ001.n3](http://eulersharp.sourceforge.net/2004/04test/icalQ001.n3))

- `?v@en` (see e.g., [LanguageQ.n3](http://eulersharp.sourceforge.net/2004/04test/LanguageQ.n3))

3. '\\' chars in strings which does not seem allowed by either Turtle nor N3 (see e.g., [query-survey-10.n3](http://eulersharp.sourceforge.net/2004/04test/query-survey-10.n3))

4. `+` is element of a list but this does not seem to be allowed in Turtle nor N3 (see [biR.n3](http://eulersharp.sourceforge.net/2007/07test/biR.n3))

5. variables starting with numbers does not seem to be allowed in Turtle nor N3 (see [RULESfaces.n3](http://eulersharp.sourceforge.net/2010/05smml/RULESfaces.n3))

At least the first three cases seem quite useful, so I'm wondering whether they should be allowed?

**Comment by ericprud** [comment]
re 3, i see this parses ```?S str:matches "http://example\.org/.*"``` and presumably matches the regular expression ```http://example\.org/.*```. Does it also work with an escaped backslash a la ```?S str:matches "http://example\\.org/.*"```? It could be that the parser is just too permissive and fails to barf if an escape char isn't followed by an escapable char. At some point, perl added more meta-characters to regexps and the repercussions reverberated for two major versions as everyone had to clean up their ambiguous escapes. I advocate rejecting anything with invalid escapes.

**Comment by william-vw** [comment]
@ericprud Thanks for your insights, I agree that the grammar should only accept valid escape sequences. Escaping the '\\' works fine, so no. 3 is really a non issue.

We've modeled our [current N3 grammar](https://github.com/w3c/N3/tree/master/grammar) after Turtle and integrated N3 expressions so it is also quite strict about escapes within strings

Note that we started by creating an ANTLR4 [grammar for Turtle](https://github.com/w3c/N3/blob/master/grammar/turtle.g4) as well ; perhaps some of the insights gained (lexer vs. parser rules, rule ordering, antlr-specific issues) could be useful for others.

**Comment by ericprud** [comment]
You can also use the ancient and venerable yacker to experiment with and share grammars. That's how we modeled and tested the [turtleAwesome grammar](https://services.w3.org/yacker/uploads/turtleAwesome?lang=perl&text=PREFIX+wd%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0D%0A%40prefix+wikibase%3A+%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23%3E+.%0D%0APrEfIx+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0A%0D%0A%0D%0Awd%3AQ19861951+a+wikibase%3AItem+%3B%0D%0A%09rdfs%3Alabel+%22type+of+food+or+dish%22%40en+%3B%0D%0A.&action=validate+text). At the bottom of that sample validation you'll see an &lt;edit this grammar> link. You can click that and save as a new name. (Try not to tromp turtleAwesome.)

It's fussy and brittle and no longer handles wide characters, but it is handy to mock up a grammar and share it with others.

**Comment by william-vw** [comment]
While testing the new N3 grammar with the cwm test cases I came across the following cases:

1. instances of `is .. of` instead of `@is .. @of`, and `has` instead of `@has`. These cases were manually corrected (see `*_correction.txt` files). (None of the files had an appropriate `keywords` declaration.)

2. escaped characters that are not supported by Turtle (i.e., aside from `tbnrf`) (see `cwm_other/strqout.n3`). Would it make sense to support escaping arbitrary characters? .. 

3. non-encoded spaces in IRIs (see `cwm_syntax/space-in-uri.n3`). It doesn't look like this test was meant to be strict (?)

4. the `this` keyword (deprecated according to [here](https://www.w3.org/2000/10/swap/grammar/n3.n3)) (see `cwm_syntax/this-quantifiers-ref2.n3`)

**Comment by william-vw** [comment]
As an update, we decided the following during our last community group meeting: 

> 
> 
> While testing the new N3 grammar with the Eye test cases I came across the following cases:
> 
>     1. non-labeled (for lack of a better word) bnodes, i.e., `_:` (e.g., [metastaticP.n3](http://eulersharp.sourceforge.net/2004/04test/metastaticP.n3))

This was an old feature of Eye and was not deemed useful for the new N3 grammar.

> 
>     2. quick-variables annotated with datatypes and language tags, i.e.,
> 
> 
>     * `?v^^xsd:int` (see e.g., [icalQ001.n3](http://eulersharp.sourceforge.net/2004/04test/icalQ001.n3))
> 
>     * `?v@en` (see e.g., [LanguageQ.n3](http://eulersharp.sourceforge.net/2004/04test/LanguageQ.n3))
> 

Idem

> 
>     3. '\' chars in strings which does not seem allowed by either Turtle nor N3 (see e.g., [query-survey-10.n3](http://eulersharp.sourceforge.net/2004/04test/query-survey-10.n3))
> 

As mentioned by @ericprud this is a bit of a non-issue - even if this is needed (e.g., a regex within a string) one can always escape the escape char as well. So, this will not be supported.

>     4. `+` is element of a list but this does not seem to be allowed in Turtle nor N3 (see [biR.n3](http://eulersharp.sourceforge.net/2007/07test/biR.n3))
> 

Will not be supported; aside from one (old) test case it does not seem useful.

>     5. variables starting with numbers does not seem to be allowed in Turtle nor N3 (see [RULESfaces.n3](http://eulersharp.sourceforge.net/2010/05smml/RULESfaces.n3))
> 

No decision has been reached on this - several (SW) languages restrict variable strings and we are unsure why. 

It would be great to get feedback from the community on this issue - why would one want to restrict allowed characters in variable labels?

**Comment by william-vw** [comment]
Continuing the update here:
> 
> While testing the new N3 grammar with the cwm test cases I came across the following cases:
> 
>     1. instances of `is .. of` instead of `@is .. @of`, and `has` instead of `@has`. These cases were manually corrected (see `*_correction.txt` files). (None of the files had an appropriate `keywords` declaration.)

For consistency we decided to support all "verb" keywords (i.e., is .. of, has, a) and true/false both with and without `@` prefix. But any official N3 spec could indicate our preference for `@` prefixed keywords.

> 
>     2. escaped characters that are not supported by Turtle (i.e., aside from `tbnrf`) (see `cwm_other/strqout.n3`). Would it make sense to support escaping arbitrary characters? ..
> 

(already covered in prior update)

>     3. non-encoded spaces in IRIs (see `cwm_syntax/space-in-uri.n3`). It doesn't look like this test was meant to be strict (?)

We decided to support non-encoded spaces in IRIs as well - we couldn't think of a good reason not to.

>     4. the `this` keyword (deprecated according to [here](https://www.w3.org/2000/10/swap/grammar/n3.n3)) (see `cwm_syntax/this-quantifiers-ref2.n3`)

No changes to the deprecation status.

**Comment by ericprud** [comment]
> As an update, we decided the following during our last community group meeting:
> 
> > While testing the new N3 grammar with the Eye test cases I came across the following cases:
> > ...
> > 5. variables starting with numbers does not seem to be allowed in Turtle nor N3 (see [RULESfaces.n3](http://eulersharp.sourceforge.net/2010/05smml/RULESfaces.n3))
> > ```
> 
> No decision has been reached on this - several (SW) languages restrict variable strings and we are unsure why.
> 
> It would be great to get feedback from the community on this issue - why would one want to restrict allowed characters in variable labels?

Ultimately, you can use whatever can be unambiguously lexed. SPARQL aligned pretty closely with XML IDs which in turn aligned with C identifiers. A few advantages of this:

1. programmers are used to this 'cause almost all non-lisp languages have a C lineage. In practice, even if you comb through lisp, you don't find symbols starting with numbers or exotic Unicode.

2. a liberal vars lexer rule could open up more phishing attacks. Folks are used to looking for crazy stuff in strings, and typically syntax highlighters will handle that, but a variable like 99\u2060someMoreStuff could trick someone or something into thinking it was the constant 99.

3. generic tools like SQL template-query preparers are way more likely to DTRT with vars they already recognize than anything starting with integers etc.

My advice is to just adopt SPARQL variables; they're reasonably well tested and the masses aren't agitating for more ways to express their creativity.

**Comment by william-vw** [comment]
@ericprud thanks - it makes a lot of sense what you're saying.

Interestingly it seems that SPARQL is in fact less restrictive than N3, since the latter does not allow variables to start with numbers: see [N3 quickvar](https://www.w3.org/2000/10/swap/grammar/n3-report.html#quickvariable) production vs. [SPARQL varname](https://www.w3.org/TR/sparql11-query/#rVARNAME) production

But you are right that users are likely not itching to try all sorts of fancy variable schemes and it is likely best to stick with SPARQL variables.

**Comment by william-vw** [comment]
The community group has reached a consensus on all these syntax issues as described above (for variables, see associated post) so this issue is being closed.
