### ISSUE TITLE
Dropping `@is .. @of` in favor of path syntax

### ISSUE THREAD

**Issue by william-vw** [w3c/N3#23]
Related to #21 and #22. 

The N3 `@is .. @of` syntax can be utilized to follow a property in the inverse direction, e.g., `paul @is father @of william`. But, 

1. This is quite unintuitive when the predicate name implies the reading direction; e.g., `paul @is hasFather @of)`;
2. N3 has a [path syntax](https://www.w3.org/TeamSubmission/n3/#path) that supports inverse properties in any position (s/p/o).

However, the N3 path syntax only supports inverse properties [after the initial item](https://www.w3.org/2000/10/swap/grammar/n3-report.html#pathitem) in the path:

- The statement `?s :fam:hasFather^fam:hasFather ?o .` binds to `?o` all people who have the father of `?s` as their father, and is correct N3 syntax.

- But the statement `?s ^fam:hasFather ?o .` binds all children of `?s` to `?o`, i.e., everyone who have `?s` as a father, is incorrect N3 syntax.

I imagine that the path syntax was meant for starting from resources and then continuing using properties, such as in the examples provided by the N3 specs. In that context, this design decision makes sense.

But I think it would be quite easy and intuitive to use `^` for indicating the inverse of a property in general. 

A possibility involves, wherever a predicate occurs in the syntax, allowing either the "regular" predicate or its "inverse" form. (This is an easy statement to make but has repercussions at more than one location in the grammar since it also pertains to the path syntax.)

Thoughts?

**Comment by josd** [comment]
In the current N3 team submission the statement:

:s fam:hasFather^fam:hasFather :o .

is the same as:

    @forSome :_g0 .
    :s     :_g0 :o .
    :_g0     fam:hasFather fam:hasFather .

I do not see any reason to change nor extend the current N3 path grammar:

expression
    pathitem pathtail

...

pathtail
    "!" expression
    "^" expression
    void

**Comment by william-vw** [comment]
Ok, I'm interpreting your comment as "path expressions are currently a shorthand to expressing more verbose blank node statements" (?) 

This is besides the point of this post - it concerns the representation of `@is .. @of` using the path syntax, which is currently not able to do that. 

Yes, this would be syntactic sugar (implementation would be simply to invert the s/o) but so is the current path syntax.

**Comment by josd** [comment]
It is feasable to implement it in EYE and for

$ cat sample.n3 
```
@prefix : <http://example.org/sample#>.
:s ^:p :o.
```

$ eye --nope sample.n3 --pass
gives
```
@prefix : <http://example.org/sample#>.
:o :p :s.
```

I did not yet commit this in https://github.com/josd/eye
and would ask if you could update n3.g4 and run

$ java -jar target/n3TestGrammar.jar n3 sample.n3 -pos -printAST

and if fine we could declare victory and close this issue :-)

**Comment by william-vw** [comment]
@josd I updated the N3 grammar to support this syntax and added two test cases (one positive and one negative) under `N3Tests/extras`. So, I agree that we may close this issue now :-)
