### ISSUE TITLE
Syntax for Variables

### ISSUE THREAD

**Issue by domel** [w3c/N3#25]
I propose to add to $ sign the grammar like in SPARQL.
```
[143] | VAR1 | ::= | '?' VARNAME
[144] | VAR2 | ::= | '$' VARNAME
```

**Comment by william-vw** [comment]
I'm again wondering where this SPARQL design choice came from - maybe it was meant as a compatibility with prior RDF query languages? I think [SeRQL](http://archive.rdf4j.org/users/ch11.html#section-variables) considered any non-prefixed term as a variable; [RDQL](https://www.w3.org/Submission/RDQL/) used `?` as a prefix - I don't recall myself but perhaps [RQL](http://wwwconference.org/proceedings/www2002/refereed/329/index.html) used "$" to prefix variables. Maybe programming languages were used as inspiration (PHP?)

@ericprud any thoughts?

**Comment by domel** [comment]
@william-vw Yes, RQL support "$". Maybe PHP or Perl were used as inspiration too.

Note that `$abc` and `?abc` identify the same variable. So it is like syntactic sugar.

**Comment by ericprud** [comment]
I don't actually remember where it came from, but it does make it a lot easier to parse and your variable names never run afoul of reserved words. Ugly but very useful.

**Comment by josd** [comment]
+1
is now supported in EYE
https://github.com/josd/eye/commit/5aa7ea8b1749a9c912d39dc9532d1c0954ef976f

-- https://josd.github.io/ <http://josd.github.io/>

**Comment by william-vw** [comment]
During our last Skype meeting, we had a consensus to not support the '$' syntax for the following reasons:

- We are targeting compatibility with Turtle, not SPARQL _per se_
- The ability to express the same thing in multiple ways carries the risk to confuse people, and cause interoperability issues (e.g., with Cwm)
- In general, there should be two criteria for syntax decisions: (**a**) commonly used notation (in SPARQL, Turtle, ..) vs. (**b**) possible confusion for N3 authors. In N3, there are several types of variables, so having a multiple syntaxes for some types could be confusing - and we are unsure whether many people use '$' syntax in SPARQL (doesn't seem that way). So, in this case, the possible confusion seems to outweigh the common use aspect.
