### ISSUE TITLE
Aligning with Base Directions and Literals

### ISSUE THREAD

**Issue by domel** [w3c/N3#30]
FYI: https://w3c.github.io/rdf-dir-literal/

**Comment by gkellogg** [comment]
Yes, we added support for that in JSON-LD 1.1. There are two forms, but the data-type form seems to be the most favored.

```turtle
[] ex:example "פעילות הבינאום, W3C"^^i18n:he_rtl ;
   ex:isbn "978-2-290-16543-0"^^i18n:_ltr
```

A future RDF working group will need to consider the implications for the data model, and if some other syntactic representation would be better.

**Comment by william-vw** [comment]
@domel same question here - if you believe this is important for the current N3, would you take on updating the grammar to be in line with it? Else, the issue can be deferred to later.

**Comment by gkellogg** [comment]
The JSON-LD described solution wouldn't seem to require any grammar change to support it. But, it could be highlighted along the lines [JSON-LD does](https://www.w3.org/TR/json-ld11/#base-direction). The Turtle versions of those examples should work just fine in N3. Of course, there's always the potential to go further, but I think it's best to let an RDF group explore that further.

**Comment by domel** [comment]
Yes, it seems to me that we are incompatible in time. Perhaps in the future we will see solutions that will influence grammar. Now I agree with @gkellogg that there's no need to change the grammar. I think you can show it with examples, I mean mainly BCP47 based solutions.

**Comment by william-vw** [comment]
Yes, the data-type form does not seem to require changes (but the [language tag form](http://ppr.cs.dal.ca:3002/n3/editor/?formula=%40base%20%3Chttp%3A%2F%2Fexample.org%2F%3E%20.%0A%40prefix%20i18n%3A%20%3Chttp%3A%2F%2Fi18n.org%3E%20.%0A%0A%22abc%22%40he%5Ertl%20.) does, which is the one I tried).

Perhaps we can add a note on this to the spec similar to JSON-LD - and close this issue for now - at least until some working group explores it further.

**Comment by domel** [comment]
@william-vw +1 
I think that a note is needed and an example e.g. `[] ex:example "פעילות הבינאום, W3C"@he-d-rtl .`

**Comment by william-vw** [comment]
@domel I added a placeholder in [the spec](https://github.com/w3c/N3/blob/master/spec/index.html) - feel free to extend or I will add something to it later. Will close the issue for now.

**Comment by gkellogg** [comment]
> Yes, it seems to me that we are incompatible in time. Perhaps in the future we will see solutions that will influence grammar. Now I agree with @gkellogg that there's no need to change the grammar. I think you can show it with examples, I mean mainly BCP47 based solutions.

We explored BCP47 based solutions ad nauseam before determining that it just wasn't practical. There's a [draft](https://w3c.github.io/rdf-dir-literal/) which covered the different approaches. @r12a and @aphillips are the real experts here.

**Comment by domel** [comment]
Yes, good idea. Let's wait for internationalization experts. Then I will add one example and a note.
