### ISSUE TITLE
[spec] Embedding N3 in HTML documents

### ISSUE THREAD

**Issue by domel** [w3c/N3#34]
Similar to Turtle, I propose to enable N3 insertion into HTML e.g.
```
<script type="text/n3">
@prefix : <http://www.example.org/#> .
:green-goblin :enemyOf :spiderman .
</script>
```

**Comment by gkellogg** [comment]
[This is the relevant section from JSON-LD](https://www.w3.org/TR/json-ld11/#embedding-json-ld-in-html-documents). Most sections seem relevant.

[Turtle has a non-normative section](https://www.w3.org/TR/turtle/#in-html) which doesn't have as many considerations (and CDATA is obsolete).

**Comment by mielvds** [comment]
Could somebody enable the github pages for the spec so that the draft is visible without local setup?

**Comment by gkellogg** [comment]
GitHub pages is enabled, and you should be able to see the rendered spec here: https://w3c.github.io/N3/spec/.

**Comment by gkellogg** [comment]
Probably, the README should give a direct link to this, so you don't need to hunt around.

**Comment by william-vw** [comment]
> Probably, the README should give a direct link to this, so you don't need to hunt around.

Understood :-) I added a note to the [spec/README](https://github.com/w3c/N3/blob/master/spec/README.md) file.

**Comment by william-vw** [comment]
@domel would you take on adding a section on this to the current spec, similar to the JSON-LD one? Else I'll flag this issue as deferred (currently cleaning up some of the issues here)

**Comment by domel** [comment]
@william-vw : I will do that.

**Comment by domel** [comment]
done
