### ISSUE TITLE
Attaching language tags, datatype IRIs to variables, and others

### ISSUE THREAD

**Issue by william-vw** [w3c/N3#39]
There were a number of test cases in `manifest.ttl` that had a `Proposed` status:
- 04test/icalR.n3
- 04test/query-survey-11.n3
- 04test/LanguageQ.n3
- 07test/biR.n3

The first 3 attach language tags and datatype IRIs to variables, and the latter has lists with elements such as "+". The current ANTLR grammar does not support them. Due to @gkellogg 's updates to the test suite they came up again, since the statuses were removed from the test cases (I'm unsure why, since they served a purpose and were decided by the WG at the time).

I remember us talking about these cases - see our meeting on January 20th 2020 ([Drive agenda](https://docs.google.com/document/d/1A3HAUhjaVnnJ6yVbFAvIBRJQjUY9aFlQ2_bGxkD0mnE/edit)). Does anyone have any thoughts - I'd recommend turning them into negative syntax tests (or removing them altogether)

**Comment by gkellogg** [comment]
I removed `rdft:Approved` from test cases, as we haven't formally approved anything that I'm aware of, but this shouldn't have touched other statuses. If so, mea culpa.

I did notice the tests that attach language and datatypes to variables and was surprised by this The grammar certainly doesn't allow this. I'd be in favor of simply dropping it.

**Comment by mielvds** [comment]
Sorry for dropping in here out of the blue, so I'm pretty uninformed. Is this a less flexible alternative to SPARQL's `FILTER ( lang(?name) = "es" )`?
I do see some potential performance gains when allowing this. However, it's not in Turtle or SPARQL, so probably better drop it?

And if dropped, do you use https://www.w3.org/TR/rif-dtb/#func:lang-from-PlainLiteral_.28adapted_from_plfn:lang-from-PlainLiteral.29 to filter by language? Because that is important functionality.

Case and questions for datatypes are similar.

**Comment by william-vw** [comment]
> 
> 
> I removed `rdft:Approved` from test cases, as we haven't formally approved anything that I'm aware of, but this shouldn't have touched other statuses. If so, mea culpa.

No worries. Yes, maybe there should be a process in place for approving test cases - these statuses were rather informally decided after a WG meeting.

**Comment by william-vw** [comment]
> Sorry for dropping in here out of the blue, so I'm pretty uninformed. Is this a less flexible alternative to SPARQL's `FILTER ( lang(?name) = "es" )`?
> I do see some potential performance gains when allowing this. However, it's not in Turtle or SPARQL, so probably better drop it?
> 
> And if dropped, do you use https://www.w3.org/TR/rif-dtb/#func:lang-from-PlainLiteral_.28adapted_from_plfn:lang-from-PlainLiteral.29 to filter by language? Because that is important functionality.
> 
> Case and questions for datatypes are similar.

I think @mielvds raises a good point - filtering by language is an important functionality. Allowing language tags to be attached to variables (either as quantified IRIs or quick-variables) would allow us to easily do this in N3. Alternatively, a special built-in could be defined for this purpose but that wouldn't be as elegant. 

Thoughts?

**Comment by gkellogg** [comment]
There are definite use cases for this, but also more questions.

* can you bind a data type or language to a variable? A language isn’t like other RDF resources that might bind.
* could the langtag batch a literal value? String operations?

**Comment by william-vw** [comment]
> There are definite use cases for this, but also more questions.
> 
>     * can you bind a data type or language to a variable? A language isn’t like other RDF resources that might bind.
 
From a practical perspective, I suppose they'd be used as a "filter criterium" when attached to a variable in a rule, i.e., ensuring that only language strings with the given language are bound to it (analogous for data types). But yes, it likely raises issues from a semantic perspective as well, although I haven't thought about those.

>     * could the langtag batch a literal value? String operations?

Something along the lines of `?x lng:langTag "en/*"` (i.e., any type of English locale)?

**Comment by gkellogg** [comment]
I had the syntax off, so a variable can't actually match the language tag, itself, although perhaps the datatype.

```
:a :b "c"^^?d .
```

But, if we are introducing filtering, perhaps the string, or some other extension could perform more selection based on language tags.

**Comment by william-vw** [comment]
I believe the test cases used language tags and datatype IRIs in the following way:
`?x rdfs:label ?l@es .`
`?x :measurement ?m^^xsd:double` .

Hence my prior answer (re filtering of variable bindings). But you raise a good point - I suppose there would be use cases for retrieving the language tag or datatype of a literal as well. Although that could be done (perhaps less elegantly) using builtins, as with the aforementioned use case.

**Comment by doerthe** [comment]
Just to let you know what already exists:

For the first example, EYE supprts the RIF function  [func:lang-from-PlainLiteral](https://www.w3.org/TR/rif-dtb/#func:lang-from-PlainLiteral_.28adapted_from_plfn:lang-from-PlainLiteral.29). Your example above could be solved by:

```
{
?x rdfs:label ?l.
(?l) func:lang-from-PlainLiteral "es".
}
=>
{?x :has :spanishTag.}.
```
For your second example there is a cwm function you can use, [dtlit](https://www.w3.org/2000/10/swap/doc/CwmBuiltins), as an example see:

```
{
?x :measurement ?m.
(?value xsd:double)  log:dtlit ?m.
}
=>
{
?x :hasMeasurementformat xsd:double
}.
``

In general, I think it is better to use built-in functions for these kinds of cases instead of inventing shortcuts, but I am open to arguments to convince me of the opposite :).

**Comment by mielvds** [comment]
I generally agree with @doerthe. It would be syntactic sugar for those builtins anyway. And I also wonder why SPARQL didn't adopt it; it seems likely that they discussed it.
That said, for UX purposes, I see great value in having a `sparql:` builtin set, with aliases where possible. Names like "func:lang-from-PlainLiteral" and "log:dtlit" are not very sexy.

A side-note on performance and datatypes though. Typed variables could significantly increase index lookups and developer oversight, regardless of how they are implemented syntactically.  For instance, when writing ?o^^xsd:int I could direct the reasoner's optimizer to high performance integer indexes.

**Comment by william-vw** [comment]
I agree with you @doerthe although personally I do like these kinds of syntactic shortcuts :-) but maybe at this point our focus should be elsewhere at this point. This could make a nice extension though.

**Comment by doerthe** [comment]
>That said, for UX purposes, I see great value in having a sparql: builtin set, with aliases where possible.

I plan for a long time to realise that by simply having translation rules. That could also help us to decide which built-ins are importatnt, I think if SPARQL and N3 both support them and if we can find use cases, that is already an indication.

**Comment by pchampin** [comment]
I think that this syntactic sugar comes with its lot of problems, making things confusing. Taking @mielvds' last example: `?o^^xsd:int`, would you expect `?o` to be bound to (a) an integer literal (e.g. 42), or (b) only to its lexical value (e.g. the string "42")? While option (a) seems more useful, option (b) seems syntactically more consistent/intuitive -- after all, `?o` occupies the place of the lexical value, and the datatype appears "outside" the variable...

> It would be syntactic sugar for those builtins anyway. And I also wonder why SPARQL didn't adopt it; it seems likely that they discussed it.

I don't know if it was discussed or not, but I have a hunch why they didn't consider or adopt it: it requires literals in the subject position, which RDF does not support (unfortunately). N3 does not have that limitation, and can therefore happily use builtins for "destructuring" literals.

**Comment by mielvds** [comment]
> I think that this syntactic sugar comes with its lot of problems, making things confusing. Taking @mielvds' last example: `?o^^xsd:int`, would you expect `?o` to be bound to (a) an integer literal (e.g. 42), or (b) only to its lexical value (e.g. the string "42")? While option (a) seems more useful, option (b) seems syntactically more consistent/intuitive -- after all, `?o` occupies the place of the lexical value, and the datatype appears "outside" the variable...

You could indeed make a case for both (a) and (b), thus enough reason to drop it;) Like @william-vw hinted, bigger fish to fry than this discussion ;)

**Comment by william-vw** [comment]
Yes, I'd agree with @mielvds and if nobody objects then I can close this issue :-)

**Comment by gkellogg** [comment]
As an alternative to dropping things that we might later circle back to, we might tag them as “deferred”, or similar. But, if there’s really no interest in perusing these features, may as well simply close. In this case, it seems that there is some interest, but insufficient bandwidth, so maybe defer.

**Comment by william-vw** [comment]
@gkellogg good idea.
