### ISSUE TITLE
Whitespace in IRIs: cwm_syntax_space-in-uri.n3

### ISSUE THREAD

**Issue by gkellogg** [w3c/N3#40]
This changed from a positive to a negative test. The input is as follows:

```turtle
# See what a parser does with (a) a space and (b) an encoded space

@prefix : <http://example.com/baz#>.

<http://example.com/foo bar> a :C.
<http://example.com/foo%20bar> a :D.

#ends
```

The first IRI contains a space, which is allowed by the IRIREF production: `IRIREF ::= "<" ( ( [ ^<>"{}\|^`\]  - [ #x00-#x20] )  \| UCHAR \| WS) * ">"`. I believe I referenced the rationale for this from the Team Submission before:

> Whitespace may not be inserted within a token, except that it may be freely added and removed whitespace within a URI between angle brackets. This allows complex URIs to be broken onto several lines, which in turn allows N3 to be sent for example of email systems in which a limited line length.

> All URIs are quoted with angle brackets. Whitespace within the <> is to be ignored. Whitespace may therefore be used on output to split a long URI between lines.

So, I believe that this input is valid, and would result in the following N-Triples:

```turtle
<http://example.com/foobar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/baz#C> .
<http://example.com/foo%20bar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/baz#D> .
```

So, the test should be changed back to a `test:TestN3PositiveSyntax`, if not a evaluation test.

**Comment by william-vw** [comment]
Aha, yes .. Good point. We should really add that to the current spec..

Just out of curiosity, how is your system solving this? Does your grammar actually allow whitespaces but do you then remove them afterwards? Or do you perform some pre-processing elsewhere?

Re the test case, I'd recommend turning it into an evaluation test, since there's expected output that should be matched (A separate syntax test could simply check whether whitespace is accepted; or we leave that syntax-test as a side-effect of the eval test?)

**Comment by gkellogg** [comment]
Yes, I basically use the production I cited, and then remove whitespace from the resulting token. (See https://github.com/ruby-rdf/rdf-n3/blob/ae834f6aed499a9a273e19ede58c88c88c91dfd4/lib/rdf/n3/reader.rb#L604-L610).

    def read_iri
      token = @lexer.first
      case token && token.type
      when :IRIREF then prod(:iri)  {process_iri(@lexer.shift.value[1..-2].gsub(/\s/, ''))}
      when :PNAME_LN, :PNAME_NS then prod(:prefixedName) {process_pname(*@lexer.shift.value)}
      end
    end

**Comment by gkellogg** [comment]
That should probably be `/\s*/m` to look for newlines as well, so a test case such as the following could be useful.

```turtle
<http://example.com/iri with
whitespace is
okay
> a :testcase .
```

Which should result in `<http://example.com/iriwithwhitespaceisokay> rdf:type <#testcase> .`

**Comment by william-vw** [comment]
> 
> 
> Yes, I basically use the production I cited, and then remove whitespace from the resulting token. (See https://github.com/ruby-rdf/rdf-n3/blob/ae834f6aed499a9a273e19ede58c88c88c91dfd4/lib/rdf/n3/reader.rb#L604-L610).
> 

It just occurred to me (a bit embarrassing) that I misread the updated `IRIREF` production - i.e., its explicit inclusion of `WS` tokens. Hence my question about where whitespaces are being removed .. But if they're allowed within the token, you can of course simply remove them after parsing.

**Comment by william-vw** [comment]
> 
> 
> That should probably be `/\s*/m` to look for newlines as well, so a test case such as the following could be useful.
> 
> ```turtle
> <http://example.com/iri with
> whitespace is
> okay
> > a :testcase .
> ```
> 
> Which should result in `<http://example.com/iriwithwhitespaceisokay> rdf:type <#testcase> .`

I added a test case `newline-in-uri.n3` to the N3 test cases and updated the manifest file. The test harness (and Jena+N3 system) now both ignore whitespaces in IRIREFs. 

If this is OK with you then I can close this issue.
