### ISSUE TITLE
tokenizing IRIs with whitespace and tokenizing backward implication

### ISSUE THREAD

**Issue by josd** [w3c/N3#41]
According to my understanding

```
@prefix : <http://example.com/baz#>.
:s <= :o.
:s <= p> :o.
```

should now be interpreted as

```
@prefix : <http://example.com/baz#>.
:s <= :o.
:s <=p> :o.
```

EYE can tokenize and parse this interpretation, but not the original.
Cwm can't parse both.

**Comment by gkellogg** [comment]
As mentioned on the call, there are other cases where tokens include whitespce in W3C grammars that could lead to confusion. Even in N3/Turtle, there's `:s :p .1`, where the `.` could signify the end of the statement, or the beginning of a decimal equivalent to `0.1` (there's a Turtle test case fo this, IIRC).

In SPARQL we see the following:

* `INSERT` and `INSERT DATA` requires you check first for `INSERT DATA`,
* `DELETE`, `DELETE DATA` and `DELETE WHERE`.
* `INSERT` and `INSERT DATA`.

There's also long quotes vs. quotes, which require special attention from the tokenizer.

All of these use whitespace rules, that allows any amount of whitespace between elements of the token.

Moreover, in EBNF, whitespace is not required between either Terminal or Non-Terminal productions, thus you have the common pattern of `<s><p>"0".`.

My processors either examine tokens in order with longest-match first or process rules in order when using PEG logic.

The Team Submission describes the liberal use of whitespace, even within URIs, but I don't know how much such data exists in the wild, and I would not be opposed to eliminating whitespace from within URIs that's the team concensus.
