### ISSUE TITLE
Whitespaces in IRIs

### ISSUE THREAD

**Issue by william-vw** [w3c/N3#45]
There's been some back and forth re the allowance of non-encoded white spaces (including newlines) in IRIs.

[Turtle](https://www.w3.org/TR/turtle/#sec-grammar) does not allow whitespace in their IRIs:
```
[18] IRIREF ::= '<' ([^#x00-#x20<>"{}|^`\] | UCHAR)* '>' /* #x00=NULL #01-#x1F=control codes #x20=space */
```

But, the original [N3 team submission](https://www.w3.org/TeamSubmission/n3/#whitespace) mentioned the following:
> Whitespace may not be inserted within a token, except that it may be freely added and removed whitespace within a URI between angle brackets. This allows complex URIs to be broken onto several lines, which in turn allows N3 to be sent for example of email systems in which a limited line length.

> All URIs are quoted with angle brackets. Whitespace within the <> is to be ignored. Whitespace may therefore be used on output to split a long URI between lines.

Whereas the URI syntax specifies the following (similar rationale to N3 team submission):

> In some cases, extra whitespace (spaces, line-breaks, tabs, etc.) may have to be added to break a long URI across lines.  The whitespace should be ignored when the URI is extracted.

Hence, we had previously made the [tentative decision](https://w3c.github.io/N3/spec/#whitespace) to allow whitespaces within IRIs which should be ignored by the system.

However, implementers have found practical issues with supporting whitespaces within IRIs. For instance, when combining them with backward implications #41. One could also foresee difficult-to-debug lexer errors when a stray `<` is left somewhere and a closing `>` is not found, with a lexer trying to include _all following symbols in the document_ (incl. newlines) into a single token.

It would be great to get thoughts and feedback on this issue. Within 2 weeks of posting these kinds of issues (i.e., "feedback request") the CG will make a decision based on the feedback.

**Comment by gkellogg** [comment]
Note that the Turtle IRIREF freely mixes in character enumerations with character ranges, and is not well formed EBNF. I think it's better stated as follows (based on what I've put in the n3.ebnf file):

```
[139s] IRIREF                           ::= '<' ([^<>"{}|^`\]-[#x00-#x20] | UCHAR)* '>'
```

I support removing the ability to add arbitrary whitespace within an IRIREF, to correspond with other RDF syntaxes.

**Comment by josd** [comment]
Perfect and I have updated EYE accordingly.

**Comment by koo5** [comment]
my tongue-in-cheek suggestion from the other thread applies. However, removing the ability to add arbitrary whitespace and getting on with the program sounds reasonable.

**Comment by mielvds** [comment]
Yep, I'd follow Turtle as much as possible. The benefits aren't worth it

**Comment by william-vw** [comment]
We reached the following consensus in the WG meeting - let's drop non-encoded whitespaces in IRIs. Thanks everyone for contributing.
