### ISSUE TITLE
value space of math:exponentiation

### ISSUE THREAD

**Issue by gkellogg** [w3c/N3#46]
From the tests, it seems that `(2 10) math:exponentiation ?x` results in an integer, but [XPath defines math:pow](https://www.w3.org/TR/xpath-functions-31/#func-math-pow) to result in a double:

> math:pow($x as xs:double?, $y as xs:numeric) as xs:double?

Some cases it may result in an integer, but others a double, or maybe decimal. To do anything other than a double would seem to require some heuristics on the input. How do we want to define this?

Some possibilities:

* integer ^ nonNegativeInteger => integer
* integer ^ other numeric => double
* decimal ^ nonNegativeInteger => decimal
* decimal ^ other numeric => double
* double ^ any numeric => double

What do EYE and CWM do?

In keeping with SPARQL functions, we may want to standardize on the XPath `math:pow` definition.

**Comment by josd** [comment]
Both EYE and CWM   `(2 10) math:exponentiation 1024`
Here are some more results for EYE:
```
(2 10.3) math:exponentiation 1260.691879265195 .
(2.7 10) math:exponentiation 20589.113209464915 .
(2.7 10.3) math:exponentiation 27736.18790208095 .
(2.7e+20 10.3) math:exponentiation 2.773618790208184e+210 .
(200.0 103.0) math:exponentiation 1.0141204801825836e+237 .
```
Using the e:derive built-in EYE can also do complex number exponentiation such as the
Euler identity `("exponentiation" ("e" 0) (0 "pi") (-1.0 1.2246467991473532e-16)) e:derive true.`
https://github.com/josd/eye/blob/master/reasoning/complex/complex_query.n3
https://github.com/josd/eye/blob/master/reasoning/complex/complex_answer.n3

**Comment by josd** [comment]
To come back to the last example, it really make sense to have integers where the result is an integer:
`(200 103) math:exponentiation 1014120480182583521197362564300800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 .`

**Comment by josd** [comment]
It is actually very similar to math:sum
```
(1 1) math:sum 2 .
(1.0 1) math:sum 2.0 .
```
and there is no reason to make (1 1)!math:sum a xsd:double

**Comment by gkellogg** [comment]
I was going on the XPath definition of exponential ion. Addition, Multiolication and so forth have different promotion rules. I’ve created (not yet uploaded) some combinatorial tests that I think are in line with your reasoning. I’ll do the same for other operators.

**Comment by gkellogg** [comment]
I think we've settled this to use XPath function rules, and tests have been updated accordingly. I believe we can close this issue.
