### ISSUE TITLE
string:concatenation of non-string values

### ISSUE THREAD

**Issue by gkellogg** [w3c/N3#48]
string:concatenation is defined to work on string values, but is often used for other literal values. For example, the following tests:

[cwm_includes/concat.n3]()

    {
      ("CASH"^^xsd:string
       " IS "^^xsd:Name
       ("2"^^xsd:integer "3"^^xsd:unsignedShort)!math:product
       "\n"
      ) string:concatenation  :s}
    => {"Here we go"^^xsd:string log:outputString :s} .

[cwm_math/math-test.n3]()

    "3.1415926" a :testValue.
    3.1415926 a :testValue.
    "1729" a :testValue.
    1729 a :testValue.
    "0" a :testValue.
    0 a :testValue.
    "1.0e7" a :testValue.
    1.0e7 a :testValue.

    { :x a :testValue. :y a :testValue.
      (:x :y) math:sum :z.
      (:x " + " :y " = " :z ) string:concatenation ?s
    } => { ?s a :RESULT }.

The test results often assume some native transformation of these values, which is non-standard. I'd suggest that any values turned into strings be canonicalized using the forms defined for the [XSD canonical representation](https://www.w3.org/TR/xmlschema11-2/#dt-canonical-representation) of datatyped literals, although IRIs would also be expected in canonical form, for consistency.

Note, for double (for which XSD is vague) it would typically be represented by `"\-?\d+\.\d+E\-?\d+"` with no trailing or leading zeros.

In a related matter, considering how values are compared in tests, a parsed INTEGER,DECIMAL,DOUBLE should probably be represented in canonical form as well, so that calculations can compare to the literal defined in the test result, or at least, this should be mentioned in considerations when running tests.

**Comment by gkellogg** [comment]
For backwards compatibility, we probably need to break with other RDF forms and stick with a lower-case "e" for doubles, otherwise, revisit a lot of test results.

**Comment by josd** [comment]
All I can say at this moment is that for try.n3 being
```
@prefix math: <http://www.w3.org/2000/10/swap/math#>.
@prefix string: <http://www.w3.org/2000/10/swap/string#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix : <http://example.org/test#>.

{   (   "CASH"^^xsd:string
        " IS "^^xsd:Name
        ("2"^^xsd:integer "3"^^xsd:unsignedShort)!math:product
        "\n"
    ) string:concatenation ?S.
} => {
    ?S a :OK.
}.

"3.1415926" a :testValue.
3.1415926 a :testValue.
"1729" a :testValue.
1729 a :testValue.
"0" a :testValue.
0 a :testValue.
"1.0e7" a :testValue.
1.0e7 a :testValue.

{   ?X a :testValue.
    ?Y a :testValue.
    (?X ?Y) math:sum ?Z.
    (?X " + " ?Y " = " ?Z ) string:concatenation ?S.
} => {
    ?S a :RESULT.
}.
```
both
`eye --nope try.n3 --pass`
and
`cwm try.n3 --think --data`
give the same 34 answers
```
"3.1415926" a :testValue.
3.1415926 a :testValue.
"1729" a :testValue.
1729 a :testValue.
"0" a :testValue.
0 a :testValue.
"1.0e7" a :testValue.
10000000.0 a :testValue.
"CASH IS 6\n" a :OK.
"3.1415926 + 3.1415926 = 6.2831852" a :RESULT.
"3.1415926 + 1729 = 1732.1415926" a :RESULT.
"3.1415926 + 0 = 3.1415926" a :RESULT.
"3.1415926 + 1.0e7 = 10000003.1415926" a :RESULT.
"3.1415926 + 10000000.0 = 10000003.1415926" a :RESULT.
"1729 + 3.1415926 = 1732.1415926" a :RESULT.
"1729 + 1729 = 3458" a :RESULT.
"1729 + 0 = 1729" a :RESULT.
"1729 + 1.0e7 = 10001729.0" a :RESULT.
"1729 + 10000000.0 = 10001729.0" a :RESULT.
"0 + 3.1415926 = 3.1415926" a :RESULT.
"0 + 1729 = 1729" a :RESULT.
"0 + 0 = 0" a :RESULT.
"0 + 1.0e7 = 10000000.0" a :RESULT.
"0 + 10000000.0 = 10000000.0" a :RESULT.
"1.0e7 + 3.1415926 = 10000003.1415926" a :RESULT.
"1.0e7 + 1729 = 10001729.0" a :RESULT.
"1.0e7 + 0 = 10000000.0" a :RESULT.
"1.0e7 + 1.0e7 = 20000000.0" a :RESULT.
"1.0e7 + 10000000.0 = 20000000.0" a :RESULT.
"10000000.0 + 3.1415926 = 10000003.1415926" a :RESULT.
"10000000.0 + 1729 = 10001729.0" a :RESULT.
"10000000.0 + 0 = 10000000.0" a :RESULT.
"10000000.0 + 1.0e7 = 20000000.0" a :RESULT.
"10000000.0 + 10000000.0 = 20000000.0" a :RESULT.
```

**Comment by gkellogg** [comment]
If they both are based on Python default float serialization, then I could see why it could be 10000000.0 instead of 1.0e7, but we can’t leave this up to implementation choice, or we should ad a canonicalize option to the test to insure  interoperability. 

We need to specify how numbers are serialized, at least for running tests.

**Comment by gkellogg** [comment]
Moreover, 10000000.0 is a decimal value, but one part of the sum is double, so how do you demote from double to decimal?

**Comment by gkellogg** [comment]
We discussed today, that this might be undefined for N3, which could lead to either a processor error (strict mode), or implementation-defined behavior, which is not good for interoperability.

In this particular case, I think it might _not_ be an issue, as concatenation just needs to be defined over different RDF term types:
* IRIs have a lexical representation as defined by the abstract syntax.
* Blank nodes, do not, although when given an explicit blank node label, many implementations would probably use that, but I suggest that it should be explicitly undefined and raise an error.
* Literals all are defined to have a lexical representation, so their string value could be determined from that representation, but we haven't defined what a literal created as the result of a built-in operation, such as `math:sum` would be, as the resulting literal as a well-defined value, but no lexical representation. I assert that the only lexical representation that makes sense, at least for XSD datatypes, is it's canonical form (e.g., `1 + 1.0 = 2.0`). Such built-ins also need to have well-defined promotion rules.
* We could define the representation of lists easily enough, but quoted graphs would be problematic.

We might define an explicit value-to-lexical mapping for literals, with a corresponding built-in, which could be used in the definition of `string:concatenation` for how non-xsd:string values are interpreted.

The interpretation of xsd:string values for built-ins taking non-string arguments is more complicated, as the value-space of string literals does not align, but by defining specific rules of type promotion, we might achieve this. Easy enough for integer to decimal to double, string to any of these would require parsing. Similarly for time and date literals. Note that [XPath does define conversion rules](https://www.w3.org/TR/xpath-31/#dt-function-conversion) we could leverage.

**Comment by william-vw** [comment]
> We might define an explicit value-to-lexical mapping for literals, with a corresponding built-in, which could be used in the definition of string:concatenation for how non-xsd:string values are interpreted.

> The interpretation of xsd:string values for built-ins taking non-string arguments is more complicated, as the value-space of string literals does not align, but by defining specific rules of type promotion, we might achieve this. 

Yes, I think a `canonicalString` and `parseString` (which depends on what datatype is expected; so, different results can ensue for the same string) could certainly be useful. Re the latter, the XML Path link gives some intuition but there do not seem to be concrete processes (aside from mentions of `fn:number` or `fn:string`)

**Comment by gkellogg** [comment]
Looks like the definition for `fn:number` is in https://www.w3.org/TR/xpath-functions-31/#func-number. There should be a normative path for all of these concepts; we shouldn't try to break new ground if we can help it.

Also, note that [`fn:concat`](https://www.w3.org/TR/xpath-functions-31/#func-concat) is defined for all atomic types.

XPath likely defines the lexical representation of values resulting from mathematical operations, although I haven't yet found it.

**Comment by william-vw** [comment]
It looks like the linked spec [simply delegates](https://www.w3.org/TR/xpath-functions-31/#casting-from-strings) to "XML schema validation":

> The semantics of casting follow the rules of XML Schema validation. For example, "13" cast as xs:unsignedInt returns the xs:unsignedInt typed value 13.

Unsure where to find details of that casting process however.

**Comment by pchampin** [comment]
> XPath likely defines the lexical representation of values resulting from mathematical operations, although I haven't yet found it.

As I am reading it, this is what musy be applied to all arguments of `fn:concat`:
https://www.w3.org/TR/xpath-functions-31/#casting-to-string

**Comment by gkellogg** [comment]
I think we can close this issue now, although spec text probably needs to be added; tests have been updated.

**Comment by gkellogg** [comment]
Due to some discussions on a pending SPARQL test (https://github.com/w3c/rdf-tests/pull/68#issuecomment-713114317), I think we need to revise how terms are converted to strings, which affects `string:concatenation` based on [XPath Functions 3.1](https://www.w3.org/TR/xpath-functions/#casting-to-string).

* Decimal values are expressed as integers if there are no digits after the decimal point.
* Floats and Doubles as decimal if the absolute value is between `0.000001` and `1000000`. Positive or negative zero represented as `"0"` or `"-0"` respectively.

**Comment by gkellogg** [comment]
See PR #62 for an update the the vocabulary definition for this using XPath functions, and PR #61, which includes a test for this.
