### ISSUE TITLE
Path confusion (resource vs. property paths)

### ISSUE THREAD

**Issue by william-vw** [w3c/N3#49]
N3 supports paths that start from a starting "entity" resource, and then continue along a series of descriptive properties. For instance, from the W3C team submission:

`:joe!fam:mother!loc:office!loc:zip .`

Which can be translated into:

`:joe fam:mother _:b0 . _:b0 loc:office _:b1 . _:b1 loc:zip _:b2 .`

To differentiate these from property paths (such as those in SPARQL) that consist only of a series of predicates, I'll refer to these as "resource paths".

I feel there is an issue with resource paths when used in a certain way. This does not mean they are “broken”, i.e., in a sense that they are semantically ambiguous. 

Rather, their use becomes very unintuitive to me when using them in a predicate position. The following expression:

`:w   :p!:q!:r   :b .`

Would actually yield

`:p :q _:b0 . _:b0 :r _:b1 . :w _:b1 :b .`

Resource paths assume the first item in the path (`p`, in this case) is a resource to be described, but when used in the predicate position, this will much more likely be a descriptive property. This supports some fringe cases, where you are looking for predicate `_:bX` that is linked to initial predicate `:p` in a particular way. 

But in general this does not make a lot of sense to me. Especially when looking SPARQL property paths, and assuming most people will be familiar with SPARQL, I think most will have a wildly different idea of what an N3 (resource) path at the predicate position will do.

At the same time, this is only syntactic sugar of course - paths do not add expressivity to N3. But it does seem like they are being used, mostly for arithmetic expressions (e.g., see [here](https://github.com/w3c/N3/issues/33#issuecomment-669550617)).

We've already had (too) long discussions about this and would like to invite feedback from the community at this point.

**Comment by william-vw** [comment]
Assuming this is a problem, there are several solutions to this, such as disallowing resource paths in the predicate position; or interpreting it as a property path when in the predicate position.

For the latter solution however, an additional problem occurs. To be more consistent with SPARQL property paths, one needs to allow inverting the first predicate of a path in the predicate position. (This was not possible in the original grammar, since the first item in the path was assumed to be a resource to be described.) I.e., this would allow the following:

`:w    ^:p!:q     :b .`

But, this introduces an ambiguity in the grammar (thanks @gkellogg for bringing it up!). Since `^:p!:q` could be considered either part of the subject's resource path, or the start of the predicate's property path. This is because N3 (or Turtle) does not require separating subjects and predicates with a whitespace.

**Comment by koo5** [comment]
> does not require separating subjects and predicates with a whitespace
that's weird, is it useful?

**Comment by koo5** [comment]
so, some more sample-size-of-1 opinions:
i don't use sparql much, and i don't find the resource path used in predicate position unintuitive. And i hate the idea of introducing an inconsistency into the language. But: are resource and property path syntaxes sufficiently overlapping that somebody could copy&paste a bit of sparql containing property paths into n3 and it would happily parse? If so, then i'd vote to differentiate resource paths in pred position with some special syntax. If not, then maybe we should go all the way and actually support the sparql syntax with its own semantic, along with resource paths?

**Comment by koo5** [comment]
tongue-in-cheek suggestion: We cannot solve this problem at this level, to satisfaction of everyone. It's 2020, and parsing is no longer ["the solved problem that isn't"](http://jeffreykegler.github.io/Ocean-of-Awareness-blog/individual/2012/08/the-solved-problem-that-isnt-is.html)
People rolling their own parsers by hand and grammars having to cater to that is just hurting everyone in the end. Marpa would take the ambiguous grammar (there's some proof that you can't detect all ambiguous grammars), and, on an actually ambiguous input, would produce a coherent error message. This probably also assumes avoiding the antiquated distinction between tokenization and parsing.

**Comment by gkellogg** [comment]
> > does not require separating subjects and predicates with a whitespace
> 
> that's weird, is it useful?

One attribute of EBNF grammars such as N3 and Turtle is that white space is optional. Many times you see no white space common (e.g, between `”foo”` and `@en`), uncommon (e.g., between `<a>` and `<b>`) or mixed (e.g., before `;` or `.`). In this case, path components may be separated by space, which can make telling the difference between a path which is part of a subject, from an inverted predicate using `^`.

**Comment by hanscools** [comment]
>  I believe @josd and Hans Cools mentioned that they only use resource paths in the s/o position anyway (please correct me if I'm wrong!).

Indeed. I use the compact notation only in this fashion: ``s!p ≡ o`` and  ``o^p ≡ s``. This gives e.g. a nice built-up of a sequence of arithmetic expressions, avoiding blank nodes. I cannot see the use of 'resource paths' in a predicate position. It might be the safest to disallow that, also to avoid confusion with SPARQL property paths.

**Comment by koo5** [comment]
agreed, same syntaxes with different semantics - should not parse

**Comment by mielvds** [comment]
agreed on disallowing in the predicate position. So does this mean we have no compatibility with SPARQL property paths?

**Comment by pchampin** [comment]
> agreed on disallowing in the predicate position. 

+1

> So does this mean we have no compatibility with SPARQL property paths?

Note that SPARQL property paths would be a huge can of worms for N3. Beyond the trivial cases such as `^:p` and `:p/:q`, what would you make of the following *assertions*?
```
:alice :knows+ :bob.
:bob :knows* :charlie.
:charlie !:knows :dan.
:alice :likes|:hates :bob.
```
We could decide either (a) to fully support them, introducing unprecedented forms of disjunction and negation in N3, or (b) to authorize them only in the body of rules (e.g. `{?X :likes|:hates ?Y} => { ?X :knows ?Y}`), which would be oddly asymmetric.

Let's not go there... :dragon:

**Comment by mielvds** [comment]
agreed!

**Comment by doerthe** [comment]
For me it is OK to disallow it in predicate position but I would personally prefer to keep it, simply to keep the nice property of N3 that everything can be used in all positions.

**Comment by josd** [comment]
PROPOSAL: keep the semantics of paths unchanged (wrt Team Submission), regardless of the position.
Gregg: +1
PA: +0
Dominik: -0.5
William: -1
Doerthe: +1
Jos: +1
ACCEPTED (reluctantly): keep the semantics of paths unchanged (wrt Team Submission), regardless of the position.
