### ISSUE TITLE
Towards an Abstract Syntax

### ISSUE THREAD

**Issue by gkellogg** [w3c/N3#52]
I wrote something up on an Abstract Syntax for N3: https://github.com/ruby-rdf/rdf-n3/blob/develop/etc/abstract_syntax.md.

A couple of things I noted in the current spec which don't seem quite right:

* The definition of [formula](https://w3c.github.io/N3/spec/#formulas) has been changed, to include triples, as well as quantified formulae. The Team Submission [definition of Formulae](https://www.w3.org/TeamSubmission/n3/#Quoting) is what I had always understood, which is what is now described as an N3 graph. I suppose there was some discussion that led to this redefinition, but I find it confusing.
* In the [Terms section](https://w3c.github.io/N3/spec/#terms), `=>` is described as one of the **N3 triple elements**, which is not strictly true. It is a syntactic shorthand for log:implies, which resolves to an IRI.

I use _universal variables_, but this should probably be _N3 quantifiers_, as _universal variables_ also seem to be a syntactic convention, or quantified IRIs map to a kind of _variable_, and it could be shared that all quantifiers share their own namespace, be they quantified IRIs or quick variables.

I would like establish an abstract syntax in N3 to allow mappings from other syntaxes, such as JSON-LD.

**Comment by pchampin** [comment]
> I would like establish an abstract syntax in N3 to allow mappings from other syntaxes, such as JSON-LD.

:+1:

But to be fair, [Section 3](https://w3c.github.io/N3/spec/#concepts) of the current draft seems to pursue that goal already:

> The examples above as well as the examples in the remainder of this document all follow N3-turtle syntax which is also the standard syntax for N3. It is however possible, to use alternative syntaxes as long as the translation to N3 turtle syntax is clearly defined.

**Comment by gkellogg** [comment]
> But to be fair, [Section 3](https://w3c.github.io/N3/spec/#concepts) of the current draft seems to pursue that goal already:

Yes, but it does not specifically relate to the concepts of generalized triples and graphs, and as I've mentioned, the N3 triple elements conflate syntactic sugar with resource types.

And, as you've mentioned separately, I think we need to better formalize the space of quantified variables, both quantified IRIs and quick variables.

I also made some statements about the use of lists and graphs as quantifiers, which should probably be considered, and the confused definition of formulae from the Team Submission.

We should also consider the relationship with named graphs, if any. As I've mentioned, my implementation leverages named graphs.

**Comment by doerthe** [comment]
> Yes, but it does not specifically relate to the concepts of generalized triples and graphs, and as I've mentioned, the N3 triple elements conflate syntactic sugar with resource types.

It actually does, or what are you missing there? It was my intention to relate to RDF where possible.

**Comment by gkellogg** [comment]
I didn't see a reference to either "generalized triples" or "generalized graphs" in the N3 spec.

Also, the spec mentions "=>" as an N3 triple element, while it is actually syntactic sugar for "log:implies" (as "<=" is sugar for "is log:imples of"). Of course implication plays a larger part in N3 than other builtins, but from an abstract syntax perspective, it is just another IRI used as a predicate.

**Comment by doerthe** [comment]
I included => instead of log:implies on purpose since in my opinion the implication is more than a predicate, it is an operator, and I would like to distinguish here. But you are right, I should at least mention the log:implies here. 

For the <= it is more tricky since I do not plan to include "is ... of" in the semantics (again syntactic sugar). But coming from there, I am now actually wondering whether I should include <= at all in that section since from a semantic point of view it as also syntactic sugar.

I will think about it and write again when I have an updated version. Then we can further discuss.

**Comment by domel** [comment]
The differences between operators and predicates are very smooth. I think that leaving => as a syntactic sugar of log:implies can be useful.

**Comment by gkellogg** [comment]
Yes, but for the abstract syntax, there is really no difference between a builtin and an IRI. It's just that the IRI denotes a builtin, and log:implies has a special place. It might be worth an editorial comment about that, or point out that predicate IRI may denote a builtin with its own defined semantics, but IMO, the abstract syntax should expand on RDF 1.1 Concepts and stick to the primitive resource types. Builtins have a defined semantics, but that operates at a layer above the abstract syntax.

I'm all for the syntactic sugar, but I don't think this formally belongs in the abstract syntax.

From the Abstract to [RDF 1.1 Concepts and Abstract Syntax](https://www.w3.org/TR/rdf11-concepts/):

> This document defines an abstract syntax (a data model) which serves to link all RDF-based languages and specifications. The abstract syntax has two key data structures: RDF graphs are sets of subject-predicate-object triples, where the elements may be IRIs, blank nodes, or datatyped literals.

At the most basic level, we simply extend the set of elements to include variables and graphs.
