### ISSUE TITLE
Accept ",;" at the end of an object list

### ISSUE THREAD

**Issue by pchampin** [w3c/N3#57]
\<rant>Why on earth, JSON, don't you accept a comma after the last element of an array!!! :angry:\</rant>

Sorry for the seemingly unrelated rant :wink: but this is to explain the rationale of this issue.
Turtle, and N3, both accept a semicolon followed immediately by a period, as in
```
<s>
  <p1> <o1>;
  <p2> <o2>;
  <p3> <o3>; # ← here
.
```
And this is a *very good thing*, as it makes it possible to add / remove / insert / reorder lines in such a list of statements.

Now, strangely, Turtle does not allows this between commas and semicolons, so that I have to write
```
<s>
  <p1>
    <o1>,
    <o2>,
    <o3>; # ← ouch
.
```
which makes the file more brittle when editing. I would like to be able to write:
```
<s>
  <p1>
    <o1>,
    <o2>,
    <o3>,
  ;
.
```

Unless this adds an ambiguity that I am missing (or huge complexity to the parsers), I think it would be beneficial to add this to the N3 grammar.

**Comment by wwaites** [comment]
In most languages this can be solved with some simple formatting. In
some languages it is even idiomatic:

    [ a
    , b
    , c
    , d
    ]

In this way you can easily add or remove elements and there is no need
for a semantically suspect trailing comma.

**Comment by pchampin** [comment]
@wwaites 
> In this way you can easily add or remove elements

not entierly: the first line (instead of the last line) is a special case, so the problem remains...

**Comment by gkellogg** [comment]
The grammar rules are consistent between SPARQL, Turtle and N3:

```
[7] predicateObjectList               ::= verb objectList ( ";" ( verb objectList)? )*
[8] objectList                        ::= object ( "," object )* 
```

and for SPARQL:

```
[77]  PropertyListNotEmpty    ::= Verb ObjectList ( ';' ( Verb ObjectList )? )*
[86]  ObjectListPath          ::= ObjectPath ( ',' ObjectPath )*
```

We certainly _could_ redefine `objectList` as `object ( ',' object? )*`, but I don't think we should diverge needlessly from established practice.

**Comment by pchampin** [comment]
"needlessly" is the key here, I really need this :wink:

More seriously, I agree that being able to copy-paste N3 fragments to Turtle / SPARQL is a valuable feature, which should not be carelessly broken. But there are already a number of N3 facts (not even considering rules) that can not be copied that way:
```
42 a :EvenNumber.
:alice!:drives a :VWBeatle.
```

Plus, giving a nudge to the other syntaxes to evolve in the "right" direction could also be a good idea :stuck_out_tongue:
