### ISSUE TITLE
Replace doc:Work with void:Dataset?

### ISSUE THREAD

**Issue by gkellogg** [w3c/N3#60]
We discussed the use of `doc:Work` as a super-class for `log:N3Document` to reflect that `log:N3Document` seems to be the class of objects that can be dereferenced to retrieve N3 formulae. But, the doc namespace comes from [PIM](https://www.w3.org/2000/10/swap/pim/) and is pretty archaic. Since then, VoID and DCAT ontologies have emerged, and in particular, [void:Dataset](https://www.w3.org/TR/void/#dataset) may be a better fit. As an example:

```turtle
:DBpedia a void:Dataset;
    void:feature <http://www.w3.org/ns/formats/RDF_XML>;
```

describes that the `DBpedia` resource is available in RDF/XML, but http://www.w3.org/ns/formats/N3 also describes N3 as a format, so, generically, might be more appropriate. Particularly, for `log:semantics`, in which the domain could be `void:Dataset` instead of `doc:Work`.

**Comment by domel** [comment]
Or the second option is to define a class:
```
log:Document a rdfs:Class;
   owl:sameAs <http://www.w3.org/2000/10/swap/pim/doc#Work> .
```
And then use `log:Document` instead of `doc:Work`.

**Comment by gkellogg** [comment]
We could certainly create `log:Document`, but I think we should abandon `doc:Work`; it's part of PIM, and doesn't seem relevant any more. `void:Dataset` does seem appropriate to me, so maybe `log:Document` is a subclass of `void:Dataset`.

**Comment by domel** [comment]
@gkellogg yes, you are right, void:Dataset seems to be better.

**Comment by gkellogg** [comment]
Perhaps:

```turtle
log:Document a rdfs:Class; owl:equivalentClass void:Dataset .

log:N3Document a rdfs:Class, log:Document;
  owl:subClassOf [
    a owl:Restriction;
    owl:onProperty void:feature;
    owl:hasValue <http://www.w3.org/ns/formats/N3>
  ] .
```

**Comment by pchampin** [comment]
`owl:equivalentClass` is a dangerously strong statement, much like `owl:sameAs`. I am not sure that all `void:Dataset` can be called "documents" (some datasets are only reachable through a SPARQL endpoints, or fetchable in different parts). Also, it seems to me that a `void:Dataset` could be available in different formats, while a given "document" has a fixed format, IMHO. So I would prefer stating that `log:Document` is a subclass of `void:Dataset`.

On the other hand, I would be happy to consider that *any* `log:Document` in the N3 format is a `log:N3Document`. This would give
```
log:Document a rdfs:Class; rdfs:subClassOf void:Dataset .

log:N3Document a rdfs:Class, owl:unionOf (
  log:Document
  owl:subClassOf [
    a owl:Restriction;
    owl:onProperty void:feature;
    owl:hasValue <http://www.w3.org/ns/formats/N3>
  ] 
).
```

**Comment by william-vw** [comment]
From a reasoner standpoint, @gkellogg 's expression makes a lot of sense:
```
log:N3Document a rdfs:Class, log:Document;
  owl:subClassOf [
    a owl:Restriction;
    owl:onProperty void:feature;
    owl:hasValue <http://www.w3.org/ns/formats/N3>
  ] .
```

A reasoner will infer the "N3" feature for any document of type N3Document. (A subclass relation indicates a necessary condition; the inference explicates the assumption that any N3Document must have this feature (but it may not be present in the current graph, as per OWA).)

If you'd make it an equivalent class:

```
log:N3Document a rdfs:Class, log:Document;
  owl:equivalentClass [
    a owl:Restriction;
    owl:onProperty void:feature;
    owl:hasValue <http://www.w3.org/ns/formats/N3>
  ] .
```
The reasoner can additionally infer the N3Document type for *any* document that has the N3 feature. (An equivalency relation indicates a necessary *and* sufficient condition, i.e., having the N3 feature is sufficient for being an N3Document.)

Feel free to try it out: 

[n3doc.txt](https://github.com/w3c/N3/files/5340192/n3doc.txt)

**Comment by pchampin** [comment]
NB: I edited my last snippet above to remove a spurious `subClassOf` that came from a careless copy-paste

> The reasoner can additionally infer the N3Document type for any document that has the N3 feature. (An equivalency relation indicates a necessary and sufficient condition, i.e., having the N3 feature is sufficient for being an N3Document.)

absolutely. However, your axiom makes *anything* that has the N3 feature an N3Document. In my example, the equivalence is conveyed by the `owl:unionOf`: N3Document is (equivalent to) the union of Document and anything-with-the-N3-feature.

**Comment by william-vw** [comment]
> However, your axiom makes anything that has the N3 feature an N3Document.

Yes, indeed.

Wouldn't a union mean that an N3Document could just be a Document as well (i.e., doesn't need the N3 feature)?

You could change it to the intersection of Document and anything with the N3 feature.
________________________________

**Comment by william-vw** [comment]
> However, your axiom makes anything that has the N3 feature an N3Document.

Yes, indeed.

Wouldn't a union mean that an N3Document could just be a Document as well (i.e., doesn't need the N3 feature)?

You could change it to the intersection of Document and anything with the N3 feature:

[n3doc.txt](https://github.com/w3c/N3/files/5341518/n3doc.txt)

**Comment by pchampin** [comment]
Yes of course, I meant `owl:intersectionOf`! Sorry for the confusion...

**Comment by domel** [comment]
Can I add the last William's proposal to log.n3?

**Comment by william-vw** [comment]
We seem to have lost track of this ..

I created the following commit: accefaf
