### ISSUE TITLE
Equivalent of map(list, function) in N3?

### ISSUE THREAD

**Issue by pchampin** [w3c/N3#75]
I found myself several time in the need of a "map" function in N3, i.e. something that would apply the same operation to all members of a list, and return a list of the results.

For example
```
  ( ( 1 -2 3 ) math:absoluteValue )  log:map  ?results.
```
would bind `?results` to `(1 2 3)`.

Is there anything similar in the current builtins?
If not, could we imagine to define it?

Of course, things may get messy if the predicate passed as the second argument has multiple values for one of the elements of the list...

**Comment by gkellogg** [comment]
Quantification would seem to handle this, although for all members that match a criterion, not a select set.

**Comment by pchampin** [comment]
Well, the criterion could of course be `(1 -2 3) list:member ?x` :)

My problem is not so much to match every member of the list, but to **build a new list** with all the results.

A use-case would be string:concatenate. I advocated in #74 to *not* do an implicit cast to string, and leave it to the user. That would call for a way to map a list of arbitrary values to a list of corresponding string, e.g.:

```
{ ((1 -2 3) sfn:str)!log:map string:concatenate ?result } => { :RESULT :IS ?result }
```
(assuming `sfn:str` is recognized as a builtin for SPARQL-like string conversion)

**Comment by josd** [comment]
For this one one could use the proposed log:findall. I guess the idea of it
could be based on
http://eulersharp.sourceforge.net/2003/03swap/log-rules.html#findall
So a simple example is going from (5 3 -2 6) to (-5 -3 2 -6) using the
following rule
{ ?SCOPE e:findall (?y { (5 3 -2 6) list:member ?x. ?x math:negation ?y }
?r) } => { :list7 :out ?r } .
which would entail
:list7 :out (-5 -3 2 -6).

Jos

-- https://josd.github.io/ <http://josd.github.io/>

**Comment by william-vw** [comment]
I do like the idea of a `log:map`, it would be very useful!

Its scope would be more restricted than a general `e:findall` (or `log:collectAllIn` as it is called in the [wish list](https://docs.google.com/document/d/1ByEWSADIvebHRrBda0HhdKhHhp444mYM7BAapXVIJoM/edit#heading=h.gjdgxs) :-). I.e., it would only consider the subject list (well, 1st element of it), and the latter could possibly work on the entire document. (Jos' example only operates on the theory boxes of the builtins, of course).

I suppose it'd be relatively simply for the likes of Eye (i.e., supporting backward rules) to define a `log:map` in terms of `e:findall`.

**Comment by gkellogg** [comment]
It seemed to me that it was conceptually similar to `list:iterate`, but I couldn't make a test that worked for it, which might point to something we're missing.

**Comment by josd** [comment]
It is indeed a nice built-in and it is currently added in Release
v21.0312.1751 · josd/eye (github.com)
<https://github.com/josd/eye/releases/tag/v21.0312.1751>
So now for
{ ((5 3 -2 6) math:negation) log:map ?r } => { :list7 :out ?r } .
eye gives
:list7 :out (-5 -3 2 -6).

Jos

-- https://josd.github.io/ <http://josd.github.io/>

**Comment by pchampin** [comment]
Awesome @josd , thanks :)

I realize just now that `list:` would probably be a better namespace than `log:`...

**Comment by josd** [comment]
Yes indeed @pchampin and it is now changed in https://github.com/josd/eye/releases/tag/v21.0315.2105
Thanks :)
