### ISSUE TITLE
Semantics of cited formulas

### ISSUE THREAD

**Issue by doerthe** [w3c/N3#8]
Related to: #1 

We need to agree how to interpret cited graphs like for example

:x :says {:s :p :o}.

I think this topic is quite challenging (for TriG, for example, there was no agreement https://www.w3.org/TR/rdf11-datasets/). RDF* [4] reduces such constructs to rdf reification which  unfortunately doesn't solve the problem of defining a semantics since reification is excluded in rdf semantics (see: https://www.w3.org/TR/rdf11-mt/#reification). There are many different approaches we could follow like for example KIF [5], Common Logic [6] or also make it more complex like they do in SUMO [7].

[4] O. Hartig, B. Thompson, Foundations of an alternative approach to reification in RDF, CoRR abs/1406.3399. arXiv:1406.3399. URL http://arxiv.org/abs/1406.3399

[5] P. Hayes, C. Menzel, A semantics for the knowledge interchange format, in: IJCAI 2001 Workshop on the IEEE Standard Upper Ontology, Vol. 1, 2001, p. 145.

[6] ISO/IEC 24707:2007 Information technology – Common Logic (CL), standards.iso.org/ittf/PubliclyAvailableStandards/c039175_ISO_IEC_24707_2007%28E%29.zip (2007).

[7] C. Benzmüller, A. Pease, Higher-order aspects and context in sumo, Web Semantics: Science, Services and Agents on the World Wide Web 12 (2012) 104–117.

**Comment by william-vw** [comment]
Yeah, it looks like the [W3C Working Group on RDF dataset semantics](https://www.w3.org/TR/rdf11-datasets/) discussed for about half a year and never reached a consensus .. One could be pessimistic and say there is a small chance that we'd be able to reach consensus in the year that we took out for N3 standardization. 

On the other hand, we're only debating their interpretation for N3 in particular and not RDF in general. Indeed, it seems that a major issue the WG faced was that very different assumptions existed among [RDF] practitioners and choosing one or another of the propositions before would have gone against some deployed [RDF] implementations.

In light of this, it wouldn't be a bad idea to ask people who are acquainted with how existing N3 implementations deal with embedded formulas, and/or how they would prefer the N3 standard to deal with them.

Personally my preference would go towards having each [named graph define its own context](https://www.w3.org/TR/rdf11-datasets/#each-named-graph-defines-its-own-context) - but I feel that any solution must take care not to put a huge burden on N3 implementations (e.g. avoiding the possibility for complex nestings of formulas as discussed by Benzmüller).

**Comment by doerthe** [comment]
Just to add something to the discussion here: The [TPLP paper](https://www.csee.umbc.edu/courses/graduate/691/spring12/03/papers/n3logic-tplp.pdf) about N3 claims that nested formulas are not “referentially transparent”. This means that even if two terms in a cited formula denote the same object in the domain of discourse two cited formulas which only differ in the use of these two terms should be considered as different.

As a concrete example consider the following:

`:LoisLane :believes {:Superman :can :fly.}.`

Even if we know that the term `:Superman` denotes the same object as `:ClarkKent`, this knowledge combined with the above formula should **not** imply the following formula:

`:LoisLane :believes {:ClarkKent :can :fly.}.`

In the concrete example `:LoisLane` might not know that `:ClarkKent` denotes the same resource as Superman.

The problem is known as the ["superman problem"](https://www.w3.org/2001/12/ attributions/#superman
)  and was discussed in many contexts.

Direct question: Do we agree on that? 

I do, but would like to hear opinions.

**Comment by doerthe** [comment]
As a result of the discussion we had in our last meeting (1.7.2019) I would like to add that I see some advantages in keeping the above "lack of referential transparency": I think it is a rather weak semantics in the sense that there are not many direct conclusions which can be drawn from simple cited formula.  This "weakness" is in my opinion an advantage: If N3 assumes as little as possible, everyone who wants to have some more meaning and implications can have rules to support such stronger semantics. 

For the superman-example above, we can for example add:
```
:LoisLane :believes {:Superman :can :fly.}.

:Superman owl:sameAs :ClarkKent.


{
:LoisLane :believes {?s1 ?p2 ?o1}.
?s1 owl:sameAs ?s2.
}
=>
{
:LoisLane :believes {?s2 :can ?o1}.
```

and get that:

```
:LoisLane :believes {:ClarkKent :can :fly}.
```

Of course this is a very basic example and we would have to look deeper into that matter to know which kinds of derivations are possible,

**Comment by doerthe** [comment]
In the above context, we also discussed in our last meeting (1.7.2019) how the scope of blank nodes in cited formulas should be. As we already had this discussion in another tread (see #5), I try to keep it short here. 

Does:

`:LoisLane :believes {_:x :can :fly.}.`

Mean:

a) `∃x: believes (LoisLane, can(x,fly))`
_"There exists someone from which whom LoisLane believes that he or she can fly"_

or

b) ` believes (LoisLane, (∃x: can(x,fly)))`
_"There  LoisLane believes that there exists someone who can fly"_

[The N3 specification](https://www.w3.org/TeamSubmission/n3/#bnodes)  says that b is correct. We discussed the arguments for both sides:

It seems that TriG also follows this approach for named graphs, see [here](https://www.w3.org/TR/trig/#terms-blanks-nodes).

But: in the [lists of possible semantics](https://www.w3.org/TR/2014/NOTE-rdf11-datasets-20140225/) there are also counter examples. Without a proper semantics, we cannot really say anything here.

In this context we also discussed that one problem with the global scope of cited formulas is, that if such cited formulas refer to existing graphs in the Web, think for example in something like

`<concreteGraphUri> :containsTriples {:a :b :c. _:x :p :o}.`

the scope of `_:x` is local. 

As a solution it was proposed to simply not allow such cases and say that we can only use blank nodes to name graphs.

This is in my opinion no solution (not here, but also not for named graphs), because such a blank node can still refer to a concrete graph (remember that blank nodes are simply  existentially quantified variables) and I think in many cases this is also what we want. 

By assuming the quantifier of the cited formula on top level, we loose the expressivity to even state that a triple containing a blank node is in a formula. More concrete, let's assume that we have a `:graph1` which contains the triple

`_:x a :Unicorn.`
_"Unicorns exist."_

If we assume all existential variables to be quantified on top level, there is no way to express in N3 that `:graph1` stated that unicorns exist. If we write:

```
:graph1 :states {_:x a :Unicorn.}.
```
that statement means (assuming quantification on top level):
_"There exists something, about which graph 1 states that this is a unicorn."_

this is a totally different statement then we wanted to make. 


A last argument I would like to add here in favor of interpretation b is that it would be easier for rules. I could be wrong, but I think that users would expect that a rule having a blank node in the antecedence can actually be applied. Consider the following example:

We have a triple: 
`:bob a :Unicorn.`

And a rule:
```
{_:x a :Unicorn.} => {:world a :MagicPlace}.
``
Following interpretation a, this rule means

`∃x:  (type(x, Unicorn) → type (world, MagicPlace)`

_"There exists something and if this something is a unicorn, then the world is a magic place."_

With this rule we can not draw any conclusion from our triple. 

But, if we assume local scoping, namely interpretation b, than we have here:

`(∃x:  type(x, Unicorn) → type (world, MagicPlace)`

_"If unicorns exist, then the world is a magic place"_

With this interpretation, we could derive the triple:

`:world a :MagicPlace`

and at least I think that is also what the users of N3 will expect (but here I am also asking you).

So, my "short" summary is not short at all, sorry for that. I am still interested in your opinions.

**Comment by william-vw** [comment]
@doerthe I'm having trouble getting the desired results for your example in Cwm:

```
@prefix owl: <http://www.w3.org/2002/07/owl#>.
@prefix log: <http://www.w3.org/2000/10/swap/log#>.
@prefix : <#>.

:LoisLane :believes {:Superman :can :fly.}.
:Superman owl:sameAs :ClarkKent.

{ :LoisLane :believes {?s1 :can ?o1}. ?s1 owl:sameAs ?s2. }
=>
{ :LoisLane :believes {?s2 :can ?o1}. }.
```

In Eye it indeed infers that 
`:LoisLane :believes {:ClarkKent :can :fly}.`

But, note that this is no longer inferred when replacing `:can` by `?p1`.

**Comment by william-vw** [comment]
Your explanation re scoping of blank nodes makes sense to me, personally.

Just to be sure, how can one refer in N3 to a previously cited formula - I believe @gkellogg mentioned the use of `owl:sameAs`:
```
{ :Superman :can :Fly. } owl:sameAs :supflies.
:LoisLane :believes :supflies.
```

**Comment by doerthe** [comment]
> @doerthe I'm having trouble getting the desired results for your example in Cwm:
> 
> ```
> @prefix owl: <http://www.w3.org/2002/07/owl#>.
> @prefix log: <http://www.w3.org/2000/10/swap/log#>.
> @prefix : <#>.
> 
> :LoisLane :believes {:Superman :can :fly.}.
> :Superman owl:sameAs :ClarkKent.
> 
> { :LoisLane :believes {?s1 :can ?o1}. ?s1 owl:sameAs ?s2. }
> =>
> { :LoisLane :believes {?s2 :can ?o1}. }.
> ```
> 
> In Eye it indeed infers that
> `:LoisLane :believes {:ClarkKent :can :fly}.`
> 
> But, note that this is no longer inferred when replacing `:can` by `?p1`.

Yes, for technical reasons you need to add an extra triple for EYE (which I omitted, since that is EYE specific ;) ). So, to make your example run in EYE, try:

```
:LoisLane :believes {:Superman :can :fly.}.

:Superman owl:sameAs :ClarkKent.


{
:LoisLane :believes ?something.
?something log:equalTo {?s1 ?p1 ?o1}.
?s1 owl:sameAs ?s2.
}
=>
{
:LoisLane :believes {?s2 ?p1 ?o1}.
}.
```
then you will get your desired result.

**Comment by william-vw** [comment]
@doerthe Thanks, it's working in Eye now (not sure why that extra triple is needed ..) but still not in Cwm.

**Comment by william-vw** [comment]
@doerthe I think we've landed on a default semantics, which could possibly be overruled by adding some rules (as discussed at the top of this issue page, and in our RuleML paper :-) So would it be acceptable to close this issue? ..

**Comment by TallTed** [comment]
One thing that's missing from all this (not meant to reopen this issue, but relevant anywhere inference is brought up) is:

_**Who is allowed to see the data that claims `:Superman owl:sameAs :ClarkKent.`?**_

It's a fairly short list.  `:Superman`, `:ClarkKent`, `:KalEl`, `:JimmyOlsen`, `:Batman`, and `:BruceWayne`.  I think `:WonderWoman` and `:DianaPrince`, too.

There are certainly some others, but the point here is that `:LoisLane` isn't on the list (except in some particular timeframes in some particular universes within the multiverse).

As I've raised in other contexts -- it's important for members of the Rebel Alliance to be able to expose that to other members, but not to members of the Empire Stormtroopers -- and possibly vice versa, presuming that the Empire figures out that plainclothes/undercover detective work is of value.

Just because a triple (statement) is uttered or asserted somewhere, even if there's only one place for such utterances, doesn't mean that the statement should be visible to all.
