### ISSUE TITLE
Empty prefixes in test files

### ISSUE THREAD

**Issue by william-vw** [w3c/N3#82]
Most test files (e.g., [concatenation.n3](https://github.com/w3c/N3/blob/master/tests/N3Tests/string/concatenation.n3)) seem to list `@prefix : <#>` for the empty namespace, meaning the file URI will be used  for prefixed names with empty prefix (e.g., `:hello` becomes `https://github.com/w3c/N3/blob/master/tests/N3Tests/string/concatenation.n3#hello`).

But, the reference file (e.g., [concatenation-out.n3](https://github.com/w3c/N3/blob/master/tests/N3Tests/string/concatenation-out.n3)) typically lists `@prefix : <concatenation.n3#>`, meaning prefixed names with empty prefix are treated differently (e.g., `:hello` becomes `concatenation.n3#hello`).

Is the method in the first paragraph the appropriate way of dealing with the `<#>` namespace? If so, should we update the test files to include the appropriate URI for the empty prefix?

**Comment by gkellogg** [comment]
There's a long standing practice in N3 of the empty prefix mapping to `<#>`. From the Team Submission:

> The empty prefix "" is by default , bound to "#" -- the local namespace of the file. The parser behaves as though there were a

>    @prefix : <#>.

> just before the file. This means that <#foo> can be written :foo and using @keywords one can reduce that to foo.

I don't believe we've moved this to the spec, and it is not the practice for Turtle to have a default empty prefix.

So, in the result files, because the empty prefix would otherwise be bound to the IRI of the result file, it needs to be re-mapped to be the same as the input file.

**Comment by william-vw** [comment]
> So, in the result files, because the empty prefix would otherwise be bound to the IRI of the result file, it needs to be re-mapped to be the same as the input file.

My question: if the file URI should be used for prefixed names with empty prefix in the test file (e.g., `:hello` becomes `https://github.com/w3c/N3/blob/master/tests/N3Tests/string/concatenation.n3#hello`), then mapping the prefix to the filename alone in the output file is insufficient (e.g., `:hello` becomes `concatenation.n3#hello`)

**Comment by gkellogg** [comment]
No, it is sufficient, as RFC 3986/7 provide a means of [establishing the base](https://tools.ietf.org/html/rfc3986#section-5.1) which includes a hierarchy. Just as an `@base` following a previous `@base` is resolved according to the in-effect base IRI, so is it resolved against the document location.

If the file is at `https://github.com/w3c/N3/blob/master/tests/N3Tests/string/concatenation.n3`, then that becomes the "URI used to retrieve the entity". There is no encapsulating entity (unless it is contained in an HTML script element), so the base IRI embedded in the content establishes the base IRI for everything following. If it, itself, is a relative-reference, it is resolved using the same rules.

* Doc location: `https://github.com/w3c/N3/blob/master/tests/N3Tests/string/concatenation.n3`
* `@base`: `#`
* effective base: `https://github.com/w3c/N3/blob/master/tests/N3Tests/string/concatenation.n3#`

**Comment by william-vw** [comment]
Ah I see .. I didn't realize that a namespace such as `<concatenation.n3#>` needed to be resolved relative to the base URI. Thanks!
