### ISSUE TITLE
List index origin - 0 or 1?

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/N3#93]
Contrary to most modern programming languages, the index origin for list items starts from 1 in [this draft](https://w3c.github.io/N3/ns/list.html#vocab_list_memberAt), instead of 0.  In other words, the index of the first item in a list is currently 1 instead of 0.  

I would strongly encourage this to be changed to 0, both for easier programming and to align with most modern programming languages.  While "regular people" (i.e., people not familiar with programming) normally count things starting from 1, we should not delude ourselves about who will be using N3: it will _not_ be "regular people".  It will be geeks (like us) who are accustomed to list indexes that start from 0.

**Comment by william-vw** [comment]
Yes, the only other time where I personally found this (aside from N3) was in R vectors :-) I suppose it depends on one’s background - it seems that math / statistics oriented languages such as Matlab, R and Wolfram start their arrays at 1. 

Of course, changing the starting index from 1 to 0 would break all existing N3 code that use indexes to access lists ..


William

**Comment by pchampin** [comment]
Bragging with a reference that I discovered about a week ago:
  "Why numbering should start at zero", by Edsger Dijkstra
  https://www.cs.utexas.edu/users/EWD/ewd08xx/EWD831.PDF

> Of course, changing the starting index from 1 to 0 would break all existing N3 code that use indexes to access lists ..

That's also true :-/
