### ISSUE TITLE
`tests/manifest.ttl` includes a non existing manifest

### ISSUE THREAD

**Issue by aucampia** [w3c/N3#98]
`tests/manifest.ttl` includes:

https://github.com/w3c/N3/blob/c44d123c5958ca04117e28ca3769e2c0820f72e6/tests/manifest.ttl#L11-L16

But there is no file [`N3Tests/manifest.ttl`](https://github.com/w3c/N3/blob/c44d123c5958ca04117e28ca3769e2c0820f72e6/tests/N3Tests/manifest.ttl)

**Comment by gkellogg** [comment]
Yes, this looks like an error. PR #99 would seem to be the right fix.
